import test from 'node:test';
import assert from 'node:assert/strict';
import { calculateScenario as calculateRawScenario, cyclingCrankPower, parseRaceScenarioInput, runningGradeCost, type RaceScenarioInput, type ScenarioLeg } from './race-scenario';
const calculateScenario=(i:RaceScenarioInput)=>calculateRawScenario(i,new Date('2026-10-08T12:00:00Z'));
const evidence={observedAt:'2026-09-01',context:'Practiced at representative race effort',source:'Athlete log',confirmed:true};
function input(): RaceScenarioInput {
  return {name:'Explicit 10 km scenario',eventType:'run_road',startAt:null,weather:{kind:'unknown',source:'',issuedAt:null,validFrom:null,validTo:null,temperatureC:null,humidityPct:null,windMps:null},legs:[{id:'run',sport:'run',distanceM:10000,baseline:{sourceId:null,source:'manual',observedAt:'2026-09-01',context:'Flat 10 km actual in mild conditions',protocol:'Observed race average',sport:'run',metric:'pace_sec_km',value:300},target:300,targetConfirmed:true,segments:[],flatCourseConfirmed:true,timeMultiplier:1,bike:null,hrTargetBpm:null}],transitionSeconds:0,practicedCarbsGph:null,sensitivityPercent:10};
}
function bikeInput(): RaceScenarioInput {
 const i=input();i.eventType='bike_tt';const l=i.legs[0];l.id='bike';l.sport='bike';l.distanceM=40000;l.target=200;l.baseline={...l.baseline!,sport:'bike',metric:'power_w',value:250,protocol:'FTP reference only'};l.bike={totalMassKg:80,cdaM2:.3,crr:.004,airDensityKgM3:1.225,drivetrainEfficiency:.97,grossEfficiency:null};return i;
}
test('flat observed-reference run uses explicit selected target only',()=>{const i=input();i.legs[0].baseline!.value=250;const r=calculateScenario(i);assert.equal(r.durationSeconds,3000);assert.equal(r.legs[0].powerW,null);assert.equal(r.legs[0].hrTargetBpm,null);assert.equal(r.sensitivity!.lowSeconds,2700);assert.equal(r.classification,'scenario');});
test('null target, unconfirmed target and null baseline never fabricate finish',()=>{for(const change of [(l:ScenarioLeg)=>l.target=null,(l:ScenarioLeg)=>l.targetConfirmed=false,(l:ScenarioLeg)=>l.baseline=null]){const i=input();change(i.legs[0]);assert.equal(calculateScenario(i).durationSeconds,null);}});
test('nonfinite, string, impossible dates, enums and unknown fields rejected',()=>{for(const v of [NaN,Infinity,-1,'300']){const i=input();(i.legs[0] as unknown as Record<string,unknown>).target=v;assert.equal(parseRaceScenarioInput(i).ok,false);}const i=input();i.legs[0].baseline!.observedAt='2026-02-30';assert.equal(parseRaceScenarioInput(i).ok,false);assert.equal(parseRaceScenarioInput({...input(),surprise:1}).ok,false);assert.equal(parseRaceScenarioInput({...input(),eventType:'hyrox'}).ok,false);});
test('sport-specific baseline metric and protocol required',()=>{const i=input();i.legs[0].baseline!.metric='power_w';assert.equal(parseRaceScenarioInput(i).ok,false);i.legs[0].baseline!.metric='pace_sec_km';i.legs[0].baseline!.protocol='';assert.equal(parseRaceScenarioInput(i).ok,false);});
test('signed grade cost matches polynomial; uphill increases time',()=>{assert.equal(runningGradeCost(0),3.6);assert.ok(Math.abs(runningGradeCost(.1)-5.968214)<1e-10);assert.ok(Math.abs(runningGradeCost(-.1)-2.151706)<1e-10);const i=input();i.legs[0].segments=[{distanceM:10000,grade:.1,headwindMps:0,speedCapMps:null}];assert.ok(calculateScenario(i).durationSeconds!>3000);});
test('downhill no-credit default and explicit cap prevent unconstrained speed',()=>{const i=input();i.legs[0].segments=[{distanceM:10000,grade:-.1,headwindMps:0,speedCapMps:null}];assert.equal(calculateScenario(i).durationSeconds,3000);i.legs[0].segments[0].speedCapMps=4;assert.equal(calculateScenario(i).durationSeconds,2500);});
test('steep running grade unsupported, distance mismatch invalid',()=>{const i=input();i.legs[0].segments=[{distanceM:10000,grade:.2,headwindMps:0,speedCapMps:null}];assert.equal(calculateScenario(i).durationSeconds,null);i.legs[0].segments[0].distanceM=9000;assert.equal(parseRaceScenarioInput(i).ok,false);});
test('cycling work integrates realized crank watts and efficiency stays distinct',()=>{const i=bikeInput();const r=calculateScenario(i);assert.ok(r.durationSeconds!>0);assert.ok(Math.abs(r.legs[0].mechanicalWorkKj!-200*r.durationSeconds!/1000)<1e-8);assert.equal(r.legs[0].metabolicKcal,null);i.legs[0].bike!.grossEfficiency=.25;const s=calculateScenario(i);assert.ok(Math.abs(s.legs[0].metabolicKcal!-s.legs[0].mechanicalWorkKj!/.25/4.184)<1e-8);});
test('bike cap uses required power, negative gravity work becomes coasting',()=>{const i=bikeInput();i.legs[0].segments=[{distanceM:40000,grade:-.1,headwindMps:0,speedCapMps:5}];const r=calculateScenario(i);assert.equal(r.durationSeconds,8000);assert.equal(r.legs[0].mechanicalWorkKj,0);assert.ok(r.legs[0].warnings.some(w=>w.includes('braking')));});
test('headwind slows, tailwind speeds; missing mass never defaults',()=>{const i=bikeInput();const base=calculateScenario(i).durationSeconds!;i.legs[0].segments=[{distanceM:40000,grade:0,headwindMps:5,speedCapMps:null}];assert.ok(calculateScenario(i).durationSeconds!>base);i.legs[0].segments[0].headwindMps=-5;assert.ok(calculateScenario(i).durationSeconds!<base);i.legs[0].bike=null;assert.equal(calculateScenario(i).durationSeconds,null);});
test('mechanical formula has expected zero-wind force terms',()=>{const i=bikeInput();const b=i.legs[0].bike!;const p=cyclingCrankPower(10,{distanceM:100,grade:0,headwindMps:0,speedCapMps:null},b);assert.ok(Math.abs(p-(80*9.80665*.004+0.5*1.225*.3*100)*10/.97)<1e-10);});
test('swim selected pace works and no swimming fuel windows invented',()=>{const i=input();i.eventType='swim';const l=i.legs[0];l.sport='swim';l.distanceM=1500;l.target=120;l.baseline={...l.baseline!,sport:'swim',metric:'pace_sec_100m',value:115,protocol:'Pool CSS reference'};i.practicedCarbsGph=60;i.fuelEvidence=evidence;const r=calculateScenario(i);assert.equal(r.durationSeconds,1800);assert.equal(r.feedingDurationSeconds,null);assert.equal(r.carbohydrateGrams,null);assert.equal(r.legs[0].mechanicalWorkKj,null);});
test('practiced fueling requires dated evidence and is not work-derived',()=>{const i=input();i.practicedCarbsGph=60;assert.equal(calculateScenario(i).carbohydrateGrams,null);i.fuelEvidence=evidence;assert.equal(calculateScenario(i).carbohydrateGrams,50);i.legs[0].target=600;assert.equal(calculateScenario(i).carbohydrateGrams,100);});
test('HR and running watts absent without evidence and device',()=>{const i=input();i.legs[0].hrTargetBpm=[140,155];i.legs[0].runPowerTargetW=240;let r=calculateScenario(i);assert.equal(r.legs[0].hrTargetBpm,null);assert.equal(r.legs[0].runPowerTargetW,null);i.legs[0].intensityEvidence=evidence;i.legs[0].runPowerDevice='Same footpod / firmware / protocol';r=calculateScenario(i);assert.deepEqual(r.legs[0].hrTargetBpm,[140,155]);assert.equal(r.legs[0].runPowerTargetW,240);assert.equal(r.legs[0].mechanicalWorkKj,null);});
test('input and nested snapshots do not alias original',()=>{const i=input();const r=calculateScenario(i);i.legs[0].target=500;i.legs[0].baseline!.value=400;i.weather.source='changed';assert.equal(r.inputSnapshot.legs[0].target,300);assert.equal(r.inputSnapshot.legs[0].baseline!.value,300);assert.equal(r.inputSnapshot.weather.source,'');});
test('weather never creates physiological adjustment and checks complete forecast coverage',()=>{const i=input();i.startAt='2026-10-10T09:00:00Z';i.weather={kind:'forecast',source:'Explicit test forecast',issuedAt:'2026-10-08T00:00:00Z',validFrom:'2026-10-10T00:00:00Z',validTo:'2026-10-10T09:10:00Z',temperatureC:35,humidityPct:80,windMps:3};const r=calculateScenario(i);assert.equal(r.durationSeconds,3000);assert.ok(r.warnings.some(w=>w.includes('does not cover')));});
test('incomplete multi-leg event keeps total and fuel unknown',()=>{const i=input();i.legs.push({...i.legs[0],id:'run2',target:null});const r=calculateScenario(i);assert.equal(r.durationSeconds,null);assert.equal(r.feedingDurationSeconds,null);assert.equal(r.legs[0].durationSeconds,3000);});
test('parser round-trips and rejects invalid hr/rh/efficiency/duplicate ids',()=>{const i=input();assert.equal(parseRaceScenarioInput(i).ok,true);i.weather.humidityPct=101;assert.equal(parseRaceScenarioInput(i).ok,false);const b=bikeInput();b.legs[0].bike!.drivetrainEfficiency=0;assert.equal(parseRaceScenarioInput(b).ok,false);const h=input();h.legs[0].hrTargetBpm=[150,140];assert.equal(parseRaceScenarioInput(h).ok,false);h.legs[0].hrTargetBpm=null;h.legs.push({...h.legs[0]});assert.equal(parseRaceScenarioInput(h).ok,false);});

test('future observations fail against explicit clock, empty course needs confirmation',()=>{const i=input();i.legs[0].baseline!.observedAt='2099-01-01';assert.equal(parseRaceScenarioInput(i,new Date('2026-10-08')).ok,false);const j=input();j.fuelEvidence={...evidence,observedAt:'2099-01-01'};assert.equal(parseRaceScenarioInput(j,new Date('2026-10-08')).ok,false);const k=input();k.legs[0].flatCourseConfirmed=false;assert.equal(calculateScenario(k).durationSeconds,null);});
test('cycling rejects time-multiplier speed inflation and reports realized watts',()=>{const i=bikeInput();i.legs[0].timeMultiplier=.5;assert.equal(parseRaceScenarioInput(i).ok,false);i.legs[0].timeMultiplier=1;i.legs[0].segments=[{distanceM:40000,grade:0,headwindMps:0,speedCapMps:5}];const r=calculateScenario(i);assert.ok(r.legs[0].actualAveragePowerW!<200);assert.equal(r.legs[0].powerW,200);});

test('90-day product review gate applies to manual baseline and optional evidence',()=>{const i=input();i.legs[0].baseline!.observedAt='2026-01-01';assert.equal(calculateScenario(i).durationSeconds,null);const j=input();j.practicedCarbsGph=60;j.fuelEvidence={...evidence,observedAt:'2026-01-01'};j.legs[0].hrTargetBpm=[140,150];j.legs[0].intensityEvidence=j.fuelEvidence;const r=calculateScenario(j);assert.equal(r.carbohydrateGrams,null);assert.equal(r.legs[0].hrTargetBpm,null);});
test('segment outputs sum exactly to leg totals',()=>{const i=bikeInput();i.legs[0].segments=[{distanceM:20000,grade:.03,headwindMps:2,speedCapMps:null},{distanceM:20000,grade:-.03,headwindMps:-2,speedCapMps:10}];const r=calculateScenario(i).legs[0];assert.equal(r.segments.reduce((s,x)=>s+x.durationSeconds,0),r.durationSeconds);assert.equal(r.segments.reduce((s,x)=>s+x.mechanicalWorkKj!,0),r.mechanicalWorkKj);});
test('24-hour normalized timestamp rejected',()=>{const i=input();i.startAt='2026-10-08T24:00:00Z';assert.equal(parseRaceScenarioInput(i).ok,false);});
