import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader, SiteFooter } from "@/components/site-shell";
export const metadata: Metadata={title:"Free pilot: workflow and next steps | JMM",robots:{index:false,follow:false}};
const steps=[
  ["1. Account and access", "/login", "Google or email/password. An existing account links Google after signing in. No payment is collected; the pilot has 50 total accounts including staff."],
  ["2. Connect first", "/onboard?redo=1", "Authorize your own available provider or continue without a device. Review status, last import and errors. Connection alone does not prove data arrived."],
  ["3. Review the basic profile", "/onboard?redo=1&step=profile", "JMM name/email, saved or optional sex/weight, and imported completed-activity count, dates and sports. Provider weight is a suggestion to review, not an automatic overwrite. Missing information stays unknown."],
  ["4. Enter Today", "/today", "Completed onboarding opens Today on future sign-ins. A confirmed scheduled session is displayed when available. Otherwise use general guidance, check-in and conversation; no personalized load is invented."],
  ["5. Prepare personalized planning", "/onboard?redo=1&advanced=1", "Next phase: sport, experience, goal, recent tolerated training and its date, weekly time, days, equipment and relevant safety answers. Optional race/date, coach preference, travel and known training anchors. These are not prerequisites for browsing the app."],
  ["6. Review zones and baseline", "/settings", "Review source, sport and date before using heart rate, pace or power. No wearable is required. Cycling FTP is not a Stryd running-power threshold. A single observation is not a baseline."],
  ["7. Preview and confirm the cycle", "/training", "Review the goal, progression, recovery, schedule and any holds before confirming a plan. Missing safety/context information may pause personalized planning."],
  ["8. Daily coaching and recovery", "/checkin", "Report sleep, soreness, energy, motivation, stress, symptoms and available time. Review today's explanation and discuss changes. Conversation alone does not silently authorize a prescription change."],
  ["9. Publish and verify delivery", "/connectors", "Review one approved workout revision, publish through an enabled route, confirm it in Garmin Connect and on the actual watch, then check completed-activity import. Run this acceptance flow before expanding enrollment."],
  ["10. Review outcomes", "/dashboard", "Compare planned and completed work, confidence and missing data. Review goals, nutrition and recovery with the coach, then adjust the next block."],
];
const links=[
 ["Free registration","/login?mode=signup"],["Sign in","/login"],["Link Google to existing account","/login?link=1"],["Password recovery","/forgot-password"],
 ["Today","/today"],["Workout card view","/daily"],["Plan & Calendar","/calendar"],["J Koach","/coach"],["Profile and zones","/settings"],
 ["Training / baseline tests","/training"],["Check-in","/checkin"],["Progress dashboard","/dashboard"],["HYROX scenario","/hyrox"],["Races","/races"],["Race forecast","/races/forecast"],
 ["Nutrition","/nutrition"],["Sleep","/sleep"],["Blood results","/blood"],["Laboratory tests","/labs"],["DNA","/dna"],["Science","/science"],["Protocols","/protocols"],["J Metrics","/metrics"],
 ["Connections","/connectors"],["Gear","/gear"],["Reminders","/reminders"],["Help and support","/help"],["Administrator / coach dashboard","/admin"],
];
export default function PilotGuide(){return <div className="min-h-screen bg-paper"><SiteHeader/><main className="pub-container py-12 max-w-4xl space-y-8">
  <h1 className="font-display text-4xl">Free pilot: your route through JMM</h1>
  <p className="text-lg">Start simply: <strong>Sign in → Connections → Review profile → Today.</strong> Questions can be skipped. Complete the extra planning details only when you want a personalized cycle.</p>
  <section className="card space-y-3"><h2 className="font-bold text-xl">What is free, and what is capped?</h2><p>JMM collects no payment in this pilot. Fifty registered accounts total are allowed, including athletes, coaches and administrators. At capacity, existing users can still sign in, recover access and link Google. Third-party services or devices may have their own fees and authorization limits; JMM’s cap does not increase a provider’s approved capacity.</p></section>
  <section className="space-y-4"><h2 className="font-bold text-2xl">Step-by-step workflow</h2>{steps.map(([title,href,description])=><article className="card space-y-2" key={title}><h3 className="font-bold"><Link href={href} className="underline">{title}</Link></h3><p>{description}</p></article>)}</section>
  <section className="card space-y-3"><h2 className="font-bold text-xl">What providers can and cannot fill</h2><p>Strava’s authorized API can return completed activities and some athlete profile attributes. This implementation stores available Strava profile weight as reported data and summarizes imported activities; it does not automatically import every field, infer current fitness, or replace your JMM identity. See the <a className="underline" href="https://developers.strava.com/docs/reference/">official Strava API reference</a>.</p><p>Garmin offers separate Health, Activity and Training APIs through its developer program. JMM currently exposes supported file imports and the configured Intervals.icu route where enabled; a direct Garmin connection is not implemented by this onboarding change. See the <a className="underline" href="https://developer.garmin.com/gc-developer-program/">official Garmin program</a>.</p><p>Neither provider reliably supplies today’s pain/illness, life schedule, equipment access, training preferences or personal goals. Those questions belong to the later planning and daily check-in steps. Provider authorization is separate from signing in with Google.</p></section>
  <section className="card space-y-3"><h2 className="font-bold text-xl">Administrator credential controls</h2><p>Open <Link className="underline" href="/admin">Administrator → Registered accounts and sign-in access</Link>. Review every role, linked sign-in providers, onboarding status, unexpired sessions and remaining places. Send a reset to the saved email, or explicitly revoke another account’s existing sessions. Revocation is not suspension: the user can sign in again. Passwords and provider tokens are never shown. Role assignment and athlete coaching access remain separate controls.</p><p>SMTP acceptance does not guarantee inbox delivery. Provider sign-in and physical watch delivery require their own real-account acceptance tests. No shared public administrator or athlete password is used.</p></section>
  <section><h2 className="font-bold text-2xl mb-4">Tabs and direct links</h2><div className="grid sm:grid-cols-2 gap-3">{links.map(([label,href])=><Link className="rounded-lg border p-3 underline" key={href} href={href}>{label}</Link>)}</div><p className="text-sm mt-3">Protected pages require sign-in. Administrator tools require the corresponding role. A listed page does not imply that every provider, prediction or delivery function has passed live acceptance.</p></section>
</main><SiteFooter/></div>;}
