"use client";
import Link from "next/link";
import { RaceMethodology } from "./race-methodology";
import { useAuth } from "./auth";
import { SiteHeader, SiteFooter } from "./site-shell";

type Pair = [string,string];
type Section = {title:Pair;body:Pair;href:string;link:Pair};
const coaching:Section[]=[
 {title:["1. Your context comes first","1. Primero, tu contexto"],body:["Swimming, cycling, running, HYROX or triathlon: start with your sport and purpose. Connect an available service, review imported records, or enter information yourself. Initial questions are optional. Personalized planning needs reviewed experience, recent tolerated training, time and relevant safety information.","Natación, ciclismo, carrera, HYROX o triatlón: empieza por tu deporte y propósito. Conecta un servicio disponible, revisa lo importado o introduce tus datos. Las preguntas iniciales son opcionales. Un plan personalizado necesita experiencia, entrenamiento reciente tolerado, tiempo y seguridad revisados."],href:"/onboard?redo=1",link:["Review athlete setup","Revisar perfil inicial"]},
 {title:["2. A cycle with a purpose","2. Un ciclo con propósito"],body:["Review your goal, available days and session limits before confirming a cycle. Keep strength as supporting work for your sport. Review dated heart-rate, pace or power anchors when available; cycling power is not a running-power threshold. The coach and athlete can review the training mix instead of imposing one universal 80/20 split.","Revisa tu objetivo, días disponibles y límites de sesión antes de confirmar un ciclo. La fuerza complementa tu deporte. Revisa referencias fechadas de pulso, ritmo o potencia cuando existan; la potencia de ciclismo no es un umbral de carrera. Atleta y coach pueden revisar la distribución sin imponer un 80/20 universal."],href:"/training",link:["Explore training and tests","Explorar entrenamiento y pruebas"]},
 {title:["3. Today can differ from the calendar","3. Hoy puede ser distinto al calendario"],body:["Report sleep, soreness, stress, symptoms and available time. Available measurements add context; missing data stays unknown. Review the session purpose, warm-up, work, recovery and intensity limits. Symptoms or insufficient evidence can hold a session. A green check-in does not invent a workout when none is assigned.","Registra sueño, molestias, estrés, síntomas y tiempo disponible. Las mediciones disponibles añaden contexto; lo ausente sigue desconocido. Revisa propósito, calentamiento, trabajo, recuperación y límites de intensidad. Síntomas o evidencia insuficiente pueden pausar una sesión. Un chequeo verde no inventa un entrenamiento sin asignación."],href:"/today",link:["Open Today","Abrir Hoy"]},
 {title:["4. Talk, review, then confirm","4. Conversa, revisa y confirma"],body:["J Koach provides a persistent conversation with reviewable proposals for supported profile facts and workout results. You confirm changes before they are saved. A separate athlete–coach conversation supports discussion with authorized people. External AI is optional and requires the displayed consent; a chat message alone does not rewrite your plan.","J Koach conserva la conversación y propone cambios revisables para datos compatibles del perfil y resultados. Tú confirmas antes de guardar. La conversación atleta–coach permite hablar con personas autorizadas. La IA externa es opcional y requiere el consentimiento mostrado; un mensaje no reescribe tu plan."],href:"/coach",link:["Meet J Koach","Conocer J Koach"]},
 {title:["5. Fueling and recovery belong to the session","5. Alimentación y recuperación son parte de la sesión"],body:["Optional nutrition settings record dated practice, tolerance and available measurements. Shared daily guidance follows the reviewed session across supported daily views, reminders, Calendar sync and exports. Missing context constrains recommendations; recording a high intake does not authorize it for every workout. Recovery days include explicit guidance, with rest remaining a valid choice.","Los ajustes opcionales de nutrición registran práctica fechada, tolerancia y mediciones disponibles. La guía diaria compartida sigue la sesión revisada en vistas compatibles, recordatorios, sincronización de Calendar y exportaciones. La falta de contexto limita recomendaciones; registrar una ingesta alta no la autoriza para toda sesión. Los días de recuperación tienen orientación explícita y descansar sigue siendo válido."],href:"/settings",link:["Review profile and nutrition context","Revisar perfil y contexto nutricional"]},
 {title:["6. Close the loop with what actually happened","6. Cierra el ciclo con lo que realmente hiciste"],body:["Record completion, partial work, substitutions, duration and effort. Compare planned work with actual work, then discuss the next adjustment. Optional double days require explicit review and a suitable existing easy session; the second bout waits for first-session results and a newer check-in. They are not extra work automatically added to your week.","Registra sesiones completas, parciales, sustituciones, duración y esfuerzo. Compara lo previsto y lo realizado y conversa sobre el ajuste siguiente. Los dobles días opcionales requieren revisión explícita y una sesión fácil existente adecuada; la segunda espera resultados de la primera y un nuevo chequeo. No añaden trabajo automáticamente."],href:"/checkin",link:["Open the daily check-in","Abrir chequeo diario"]},
];
const racing:Section[]=[
 {title:["1. Give the scenario a real race","1. Dale una carrera real al escenario"],body:["Choose one of your saved races or enter an event, date, location and distance. Keep an official event link for your own review. A goal time stays a goal; the planner does not treat it as evidence of your current capacity.","Elige una carrera guardada o introduce evento, fecha, lugar y distancia. Guarda un enlace oficial para revisarlo. El tiempo objetivo sigue siendo una meta; el planificador no lo usa como evidencia de tu capacidad actual."],href:"/races/scenarios",link:["Open the scenario workspace","Abrir el espacio de escenarios"]},
 {title:["2. Inspect the evidence behind the numbers","2. Revisa la evidencia de los números"],body:["Review available athlete references with their source and measurement date. Add missing observations explicitly. Running, swimming and cycling need appropriate sport-specific evidence; an undated number or a value from another sport is not silently substituted.","Revisa las referencias disponibles con su fuente y fecha. Añade explícitamente las observaciones ausentes. Carrera, natación y ciclismo necesitan evidencia específica; no se sustituye silenciosamente por un dato sin fecha o de otro deporte."],href:"/races/scenarios#evidence",link:["Review race evidence","Revisar evidencia de carrera"]},
 {title:["3. Make the course visible","3. Haz visible el recorrido"],body:["Import a GPX file or enter a distance–elevation profile. Inspect the profile, climbs and descents before calculating a scenario. Course data is an input to review, and GPS or elevation errors can affect the result.","Importa un archivo GPX o introduce un perfil de distancia y elevación. Revisa perfil, subidas y bajadas antes de calcular. Los datos del recorrido requieren revisión y los errores de GPS o elevación pueden afectar el resultado."],href:"/races/scenarios#course",link:["Review a course","Revisar un recorrido"]},
 {title:["4. Change assumptions, compare scenarios","4. Cambia supuestos y compara escenarios"],body:["Explore entered temperature, weather and execution assumptions. Request available event-time weather or use clearly labeled manual conditions. Save dated scenario snapshots and compare their inputs and calculated outputs. These calculations have not been validated as individual race predictions.","Explora temperatura, meteorología y supuestos de ejecución. Consulta el tiempo disponible para el evento o utiliza condiciones manuales identificadas. Guarda escenarios fechados y compara entradas y resultados. Estos cálculos no se han validado como predicciones individuales."],href:"/races/scenarios#conditions",link:["Explore conditions","Explorar condiciones"]},
 {title:["5. Keep execution tied to observations","5. Basa la ejecución en observaciones"],body:["Inspect the pace or power outputs the available evidence can support. Heart-rate references require explicit observed inputs. Missing evidence stays visible, and unsupported outputs remain unavailable. A scenario does not replace medical advice, course rules or a coach's review.","Revisa los ritmos o potencias que permite la evidencia disponible. Las referencias de pulso requieren observaciones explícitas. Los datos ausentes se muestran y los resultados sin respaldo siguen no disponibles. Un escenario no sustituye consejo médico, reglas del recorrido ni revisión del coach."],href:"/races/scenarios#execution",link:["Review execution assumptions","Revisar supuestos de ejecución"]},
 {title:["6. Keep fueling practice separate","6. Mantén aparte la práctica nutricional"],body:["Record practiced carbohydrate intake, when you tried it and whether you tolerated it. Review this context alongside the scenario. A calculated finish time does not establish your tolerance or automatically authorize a higher intake. The separate HYROX tool remains available for run and station assumptions.","Registra carbohidratos practicados, cuándo los probaste y su tolerancia. Revisa ese contexto junto al escenario. Un tiempo calculado no demuestra tolerancia ni autoriza automáticamente una ingesta mayor. La herramienta HYROX sigue disponible para supuestos de carrera y estaciones."],href:"/science/race-fuel",link:["Read the fueling guide","Leer la guía de nutrición"]},
];
export function CoachingShowcase({kind}:{kind:"coaching"|"racing"}){
 const {language}=useAuth();const es=language==="es";const pick=(p:Pair)=>p[es?1:0];const race=kind==="racing";
 return <div className="min-h-screen bg-paper"><SiteHeader/><main className="pub-container py-12 sm:py-16 max-w-5xl">
 <p className="kicker">{race?"AdvanzedRacing":"J Koach"} · JasMiamiMethod</p>
 <h1 className="display-2xl mt-4">{race?pick(["Your race. Your evidence. Scenarios you can inspect.","Tu carrera. Tu evidencia. Escenarios que puedes revisar."]):pick(["Daily coaching built around your life and your training.","Entrenamiento diario alrededor de tu vida y tu deporte."])}</h1>
 <p className="lede mt-5">{race?pick(["Bring your race, athlete references, course and conditions into one workspace. Change an assumption and see what the calculation depends on.","Reúne carrera, referencias del atleta, recorrido y condiciones. Cambia un supuesto y revisa de qué depende el cálculo."]):pick(["Your goal sets the direction. Your check-in, available evidence and reviewed results inform the next step—with or without a wearable.","Tu objetivo marca la dirección. Tu chequeo, la evidencia disponible y los resultados revisados orientan el siguiente paso, con o sin dispositivo."])}</p>
 {race&&<aside className="mt-7 rounded-xl border border-amber-400 bg-amber-50 p-5" aria-label={pick(["Current forecast availability","Disponibilidad del pronóstico"])}><h2 className="font-bold">{pick(["Pilot status: scenario calculations are unvalidated","Estado del piloto: cálculos de escenarios no validados"])}</h2><p className="mt-2">{pick(["AdvanzedRacing lets you explore explicit race assumptions and save the resulting scenarios. These are unvalidated calculations, with no established individual prediction accuracy. The legacy personalized forecast remains disabled. Review source dates, missing evidence and every assumption before using a scenario in preparation.","AdvanzedRacing permite explorar supuestos explícitos y guardar los escenarios resultantes. Son cálculos no validados, sin precisión predictiva individual establecida. El pronóstico personalizado anterior sigue deshabilitado. Revisa fechas, datos ausentes y cada supuesto antes de usar un escenario para prepararte."])}</p></aside>}
 <div className="flex flex-wrap gap-3 mt-7"><Link className="btn-editorial" href={race?"/races/scenarios":"/login"}>{pick(race?["Prepare your race","Preparar tu carrera"]:["Start free","Empezar gratis"])}</Link><Link className="btn-secondary" href={race?"/personal-coaching":"/race-prediction"}>{pick(race?["Explore daily coaching","Explorar coaching diario"]:["Explore AdvanzedRacing","Explorar AdvanzedRacing"])}</Link></div>
 <div className="grid md:grid-cols-2 gap-5 mt-12">{(race?racing:coaching).map(s=><section className="card flex flex-col" key={s.href+s.title[0]}><h2 className="display-lg">{pick(s.title)}</h2><p className="leading-relaxed text-ink-600 mt-4 flex-1">{pick(s.body)}</p><Link href={s.href} className="mt-5 underline font-semibold">{pick(s.link)} →</Link></section>)}</div>
 {race && <RaceMethodology es={es}/>}
 <section className="mt-12 border-t border-ink-200 pt-8"><h2 className="display-lg">{pick(["More of JMM worth exploring","Más de JMM que vale la pena explorar"])}</h2><div className="grid sm:grid-cols-3 gap-5 mt-5">{[
 {title:["J Metrics, explained","J Metrics, explicadas"] as Pair,body:["Review recorded load and missing data without confusing an estimate with measured fitness.","Revisa carga registrada y datos ausentes sin confundir estimaciones con condición física medida."] as Pair,href:"/metrics"},
 {title:["Evidence you can inspect","Evidencia que puedes revisar"] as Pair,body:["Explore sources, applicable populations and limitations. A published principle is not proof of your exact training dose.","Explora fuentes, poblaciones y límites. Un principio publicado no prueba tu dosis exacta de entrenamiento."] as Pair,href:"/science"},
 {title:["A coach and an athlete, working together","Coach y atleta, trabajando juntos"] as Pair,body:["Review profiles, discuss changes and track results through authorized coaching access. Device connection and workout delivery are separate checks.","Revisa perfiles, conversa sobre cambios y sigue resultados con acceso autorizado. Conectar un dispositivo y entregar un entrenamiento son verificaciones distintas."] as Pair,href:"/how-it-works#coach-admin"}
 ].map(s=><article key={s.href}><h3 className="font-semibold">{pick(s.title)}</h3><p className="mt-2 text-sm leading-relaxed">{pick(s.body)}</p><Link className="inline-block mt-3 underline" href={s.href}>{pick(["Explore","Explorar"])} →</Link></article>)}</div></section>
 <p className="text-sm text-ink-600 mt-10">{pick(["JMM is free during the 50-account pilot. External services may have their own fees and limits. Account access is required for athlete tools. No guaranteed performance, injury prevention or watch delivery is claimed.","JMM es gratuito durante el piloto de 50 cuentas. Los servicios externos pueden tener costes y límites propios. Las herramientas del atleta requieren iniciar sesión. No se garantizan rendimiento, prevención de lesiones ni entrega al reloj."])}</p>
 </main><SiteFooter/></div>;
}

