"use client";
import Link from "next/link";
import { RaceMethodology } from "./race-methodology";
import { useAuth } from "./auth";
import { SiteHeader, SiteFooter } from "./site-shell";

type Pair = [string,string];
type Section = {title:Pair;body:Pair;href:string;link:Pair};
const coaching:Section[]=[
 {title:["1. Your context comes first","1. Primero, tu contexto"],body:["Swimming, cycling, running, HYROX or triathlon: start with your sport and purpose. Connect an available service, review imported records, or enter information yourself. Initial questions are optional. Personalized planning needs reviewed experience, recent tolerated training, time and relevant safety information.","Natación, ciclismo, carrera, HYROX o triatlón: empieza por tu deporte y propósito. Conecta un servicio disponible, revisa lo importado o introduce tus datos. Las preguntas iniciales son opcionales. Un plan personalizado necesita experiencia, entrenamiento reciente tolerado, tiempo y seguridad revisados."],href:"/onboard?redo=1",link:["Review athlete setup","Revisar perfil inicial"]},
 {title:["2. A cycle with a purpose","2. Un ciclo con propósito"],body:["Review your goal, available days and session limits before confirming a cycle. Keep strength as supporting work for your sport. Review dated heart-rate, pace or power anchors when available; cycling power is not a running-power threshold. The coach and athlete can review the training mix instead of imposing one universal 80/20 split.","Revisa tu objetivo, días disponibles y límites de sesión antes de confirmar un ciclo. La fuerza complementa tu deporte. Revisa referencias fechadas de pulso, ritmo o potencia cuando existan; la potencia de ciclismo no es un umbral de carrera. Atleta y coach pueden revisar la distribución sin imponer un 80/20 universal."],href:"/training",link:["Explore training and tests","Explorar entrenamiento y pruebas"]},
 {title:["3. Today can differ from the calendar","3. Hoy puede ser distinto al calendario"],body:["Report sleep, soreness, stress, symptoms and available time. Available measurements add context; missing data stays unknown. Review the session purpose, warm-up, work, recovery and intensity limits. Symptoms or insufficient evidence can hold a session. A green check-in does not invent a workout when none is assigned.","Registra sueño, molestias, estrés, síntomas y tiempo disponible. Las mediciones disponibles añaden contexto; lo ausente sigue desconocido. Revisa propósito, calentamiento, trabajo, recuperación y límites de intensidad. Síntomas o evidencia insuficiente pueden pausar una sesión. Un chequeo verde no inventa un entrenamiento sin asignación."],href:"/today",link:["Open Today","Abrir Hoy"]},
 {title:["4. Talk, review, then confirm","4. Conversa, revisa y confirma"],body:["J Koach provides a persistent conversation with reviewable proposals for supported profile facts and workout results. You confirm changes before they are saved. A separate athlete–coach conversation supports discussion with authorized people. External AI is optional and requires the displayed consent; a chat message alone does not rewrite your plan.","J Koach conserva la conversación y propone cambios revisables para datos compatibles del perfil y resultados. Tú confirmas antes de guardar. La conversación atleta–coach permite hablar con personas autorizadas. La IA externa es opcional y requiere el consentimiento mostrado; un mensaje no reescribe tu plan."],href:"/coach",link:["Meet J Koach","Conocer J Koach"]},
 {title:["5. Fueling and recovery belong to the session","5. Alimentación y recuperación son parte de la sesión"],body:["Optional nutrition settings record dated practice, tolerance and available measurements. Shared daily guidance follows the reviewed session across supported daily views, reminders, Calendar sync and exports. Missing context constrains recommendations; recording a high intake does not authorize it for every workout. Recovery days include explicit guidance, with rest remaining a valid choice.","Los ajustes opcionales de nutrición registran práctica fechada, tolerancia y mediciones disponibles. La guía diaria compartida sigue la sesión revisada en vistas compatibles, recordatorios, sincronización de Calendar y exportaciones. La falta de contexto limita recomendaciones; registrar una ingesta alta no la autoriza para toda sesión. Los días de recuperación tienen orientación explícita y descansar sigue siendo válido."],href:"/settings",link:["Review profile and nutrition context","Revisar perfil y contexto nutricional"]},
 {title:["6. Close the loop with what actually happened","6. Cierra el ciclo con lo que realmente hiciste"],body:["Record completion, partial work, substitutions, duration and effort. Compare planned work with actual work, then discuss the next adjustment. Optional double days require explicit review and a suitable existing easy session; the second bout waits for first-session results and a newer check-in. They are not extra work automatically added to your week.","Registra sesiones completas, parciales, sustituciones, duración y esfuerzo. Compara lo previsto y lo realizado y conversa sobre el ajuste siguiente. Los dobles días opcionales requieren revisión explícita y una sesión fácil existente adecuada; la segunda espera resultados de la primera y un nuevo chequeo. No añaden trabajo automáticamente."],href:"/checkin",link:["Open the daily check-in","Abrir chequeo diario"]},
];
const racing:Section[]=[
 {title:["Start with the race you actually entered","Empieza por la carrera que vas a hacer"],body:["Save the event, date, distance, priority, venue and your target. A goal time describes what you hope to achieve; it is not a prediction of current capacity. Keep the event tied to your training cycle so athlete and coach can review the preparation together.","Guarda evento, fecha, distancia, prioridad, lugar y objetivo. El tiempo objetivo describe lo que deseas lograr; no predice tu capacidad actual. Vincula el evento al ciclo para revisar la preparación con tu coach."],href:"/races",link:["Review your races","Revisar tus carreras"]},
 {title:["Build an evidence file, not just a finish time","Reúne evidencia, no solo un tiempo final"],body:["Review sport-specific tests, when they were measured, the conditions, recent training and interruptions. Separate measured results, self-reported references and estimates. Before forecasts can be released, the app needs validated dated anchors, event/course inputs and evaluated model error. Those checks are not complete in this pilot.","Revisa pruebas específicas del deporte, fecha, condiciones, entrenamiento reciente e interrupciones. Separa mediciones, referencias declaradas y estimaciones. Antes de publicar pronósticos se necesitan referencias fechadas, datos de evento/recorrido validados y evaluación del error. Esas verificaciones aún no están completas en el piloto."],href:"/settings",link:["Review your reference data","Revisar tus referencias"]},
 {title:["Course and conditions belong in the discussion","El recorrido y las condiciones importan"],body:["Record venue and course information and review available weather information near the event. Hills, surface, transitions and conditions can change the questions you discuss with your coach. The current pilot does not turn these inputs into a validated personalized pacing table or finish-time forecast.","Registra lugar y recorrido y revisa la información meteorológica disponible cerca del evento. Desnivel, superficie, transiciones y condiciones cambian las preguntas para tu coach. El piloto no convierte estos datos en una tabla de ritmo personalizada validada ni en un pronóstico de tiempo final."],href:"/races",link:["Prepare event details","Preparar detalles del evento"]},
 {title:["HYROX: review a scenario, then test it","HYROX: revisa un escenario y contrástalo"],body:["The HYROX split planner helps explore entered running and station assumptions. Its total is a scenario, not a validated prediction. Discuss division, station experience and equipment access, then compare actual splits and transitions with what you planned.","El planificador HYROX explora los supuestos introducidos para carrera y estaciones. El total es un escenario, no una predicción validada. Revisa división, experiencia en estaciones y material, y compara parciales y transiciones reales con lo previsto."],href:"/hyrox",link:["Explore HYROX scenarios","Explorar escenarios HYROX"]},
 {title:["Practice the execution before race day","Practica la ejecución antes de competir"],body:["Use training to discuss pacing, familiar food and drink, equipment and recovery. Keep race strategy consistent with what you have practiced and tolerated. Daily nutrition guidance and race tools are separate surfaces today; this page does not claim a unified automatic race-fueling prescription or live watch guidance.","Usa el entrenamiento para revisar ritmo, alimentos y bebidas conocidos, material y recuperación. Mantén la estrategia acorde con lo practicado y tolerado. La guía nutricional diaria y las herramientas de carrera siguen siendo superficies separadas; esta página no promete una prescripción automática unificada ni guía en vivo en el reloj."],href:"/science/race-fuel",link:["Read the race-fueling guide","Leer la guía de alimentación en carrera"]},
];
export function CoachingShowcase({kind}:{kind:"coaching"|"racing"}){
 const {language}=useAuth();const es=language==="es";const pick=(p:Pair)=>p[es?1:0];const race=kind==="racing";
 return <div className="min-h-screen bg-paper"><SiteHeader/><main className="pub-container py-12 sm:py-16 max-w-5xl">
 <p className="kicker">{race?"AdvanzedRacing":"J Koach"} · JasMiamiMethod</p>
 <h1 className="display-2xl mt-4">{race?pick(["Race preparation, with honest expectations.","Prepara tu carrera con expectativas honestas."]):pick(["Daily coaching built around your life and your training.","Entrenamiento diario alrededor de tu vida y tu deporte."])}</h1>
 <p className="lede mt-5">{race?pick(["Give your goal a course, a context and a plan. Understand what is known before trusting a number.","Dale a tu objetivo un recorrido, un contexto y un plan. Comprende lo conocido antes de confiar en un número."]):pick(["Your goal sets the direction. Your check-in, available evidence and reviewed results inform the next step—with or without a wearable.","Tu objetivo marca la dirección. Tu chequeo, la evidencia disponible y los resultados revisados orientan el siguiente paso, con o sin dispositivo."])}</p>
 {race&&<aside className="mt-7 rounded-xl border border-amber-400 bg-amber-50 p-5" aria-label={pick(["Current forecast availability","Disponibilidad del pronóstico"])}><h2 className="font-bold">{pick(["Pilot status: personalized numeric forecasts are unavailable","Estado del piloto: pronósticos numéricos personalizados no disponibles"])}</h2><p className="mt-2">{pick(["AdvanzedRacing is the name of our race-planning and forecast workspace. Finish-time forecasts, personalized course pacing and prediction accuracy are not validated or enabled in this pilot. Race records and the separate HYROX scenario planner remain available.","AdvanzedRacing es el nombre de nuestro espacio de planificación y pronóstico. Los tiempos finales, ritmos personalizados por recorrido y precisión predictiva no están validados ni habilitados en el piloto. El registro de carreras y el planificador de escenarios HYROX sí están disponibles."])}</p></aside>}
 <div className="flex flex-wrap gap-3 mt-7"><Link className="btn-editorial" href={race?"/races":"/login"}>{pick(race?["Prepare your race","Preparar tu carrera"]:["Start free","Empezar gratis"])}</Link><Link className="btn-secondary" href={race?"/personal-coaching":"/race-prediction"}>{pick(race?["Explore daily coaching","Explorar coaching diario"]:["Explore AdvanzedRacing","Explorar AdvanzedRacing"])}</Link></div>
 <div className="grid md:grid-cols-2 gap-5 mt-12">{(race?racing:coaching).map(s=><section className="card flex flex-col" key={s.href+s.title[0]}><h2 className="display-lg">{pick(s.title)}</h2><p className="leading-relaxed text-ink-600 mt-4 flex-1">{pick(s.body)}</p><Link href={s.href} className="mt-5 underline font-semibold">{pick(s.link)} →</Link></section>)}</div>
 {race && <RaceMethodology es={es}/>}
 <section className="mt-12 border-t border-ink-200 pt-8"><h2 className="display-lg">{pick(["More of JMM worth exploring","Más de JMM que vale la pena explorar"])}</h2><div className="grid sm:grid-cols-3 gap-5 mt-5">{[
 {title:["J Metrics, explained","J Metrics, explicadas"] as Pair,body:["Review recorded load and missing data without confusing an estimate with measured fitness.","Revisa carga registrada y datos ausentes sin confundir estimaciones con condición física medida."] as Pair,href:"/metrics"},
 {title:["Evidence you can inspect","Evidencia que puedes revisar"] as Pair,body:["Explore sources, applicable populations and limitations. A published principle is not proof of your exact training dose.","Explora fuentes, poblaciones y límites. Un principio publicado no prueba tu dosis exacta de entrenamiento."] as Pair,href:"/science"},
 {title:["A coach and an athlete, working together","Coach y atleta, trabajando juntos"] as Pair,body:["Review profiles, discuss changes and track results through authorized coaching access. Device connection and workout delivery are separate checks.","Revisa perfiles, conversa sobre cambios y sigue resultados con acceso autorizado. Conectar un dispositivo y entregar un entrenamiento son verificaciones distintas."] as Pair,href:"/how-it-works#coach-admin"}
 ].map(s=><article key={s.href}><h3 className="font-semibold">{pick(s.title)}</h3><p className="mt-2 text-sm leading-relaxed">{pick(s.body)}</p><Link className="inline-block mt-3 underline" href={s.href}>{pick(["Explore","Explorar"])} →</Link></article>)}</div></section>
 <p className="text-sm text-ink-600 mt-10">{pick(["JMM is free during the 50-account pilot. External services may have their own fees and limits. Account access is required for athlete tools. No guaranteed performance, injury prevention or watch delivery is claimed.","JMM es gratuito durante el piloto de 50 cuentas. Los servicios externos pueden tener costes y límites propios. Las herramientas del atleta requieren iniciar sesión. No se garantizan rendimiento, prevención de lesiones ni entrega al reloj."])}</p>
 </main><SiteFooter/></div>;
}

