"use client";
const rows=[
 ["Athlete references / Referencias del atleta","Dated sport-specific observations, with their source and context. Undated or unsuitable records remain visible as gaps.","Observaciones fechadas por deporte, con fuente y contexto. Los registros sin fecha o no apropiados se muestran como datos pendientes.","Whether a test represents sustained race effort, recent training tolerance and event-specific durability.","Si una prueba representa esfuerzo sostenible, tolerancia al entrenamiento reciente y resistencia específica del evento."],
 ["Course / Recorrido","A reviewed GPX or manually entered distance–elevation profile, including signed climbing and descending segments.","Un GPX revisado o perfil manual de distancia y elevación, con segmentos de subida y bajada.","GPS/elevation error, surface, turns, traffic, technical handling and event rules.","Error de GPS/elevación, superficie, giros, tráfico, habilidad técnica y reglas del evento."],
 ["Conditions / Condiciones","Provider weather when available for the selected event time, or explicit manual assumptions. Temperature and other conditions can be edited.","Meteorología del proveedor cuando esté disponible para la hora seleccionada o supuestos manuales explícitos. La temperatura y otras condiciones se pueden editar.","Local exposure, individual heat response and changes after the forecast was retrieved.","Exposición local, respuesta individual al calor y cambios posteriores a la consulta."],
 ["Execution / Ejecución","Inspectable scenario arithmetic from supported inputs, with missing-data reasons. Pace, power and heart rate are distinct quantities.","Cálculo de escenarios revisable con entradas compatibles y motivos de datos ausentes. Ritmo, potencia y pulso son magnitudes distintas.","Individual prediction accuracy, race-day readiness and the sustainable intensity of the chosen scenario.","Precisión predictiva individual, estado el día de carrera e intensidad sostenible del escenario elegido."],
 ["Fueling / Nutrición","Practiced carbohydrate intake and dated tolerance context, kept separate from performance calculations.","Carbohidratos practicados y contexto fechado de tolerancia, separados del cálculo de rendimiento.","Race-specific tolerance, products, access to aid stations and individual clinical requirements.","Tolerancia específica, productos, acceso a avituallamientos y necesidades clínicas individuales."]
];
export function RaceMethodology({es}:{es:boolean}){return <section className="mt-12 space-y-6" id="methodology">
 <h2 className="display-lg">{es?"Cómo leer un escenario":"How to read a scenario"}</h2>
 <p>{es?"Un escenario muestra el resultado de unos supuestos explícitos. La precisión individual de JMM aún no se ha medido en carreras independientes. Comparar condiciones no produce un intervalo estadístico ni demuestra qué ocurrirá el día de carrera.":"A scenario shows the result of explicit assumptions. Individual JMM accuracy has not been measured on independent races. Comparing conditions does not produce a statistical prediction interval or establish what will happen on race day."}</p>
 <div className="overflow-x-auto rounded-xl border border-ink-200"><table className="w-full text-sm text-left"><caption className="sr-only">{es?"Entradas, uso y límites del escenario":"Scenario inputs, use and limitations"}</caption><thead className="bg-ink-900 text-paper"><tr>{(es?["Entrada","Uso en el escenario","Qué sigue sin conocerse"]:["Input","Use in the scenario","What remains unknown"]).map(h=><th scope="col" className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t border-ink-200 align-top" key={r[0]}><th scope="row" className="p-4 font-semibold">{r[0]}</th><td className="p-4 leading-relaxed">{r[es?2:1]}</td><td className="p-4 leading-relaxed">{r[es?4:3]}</td></tr>)}</tbody></table></div>
 <div className="card space-y-3"><h3 className="font-bold text-xl">{es?"Validación pendiente":"Validation still needed"}</h3><p>{es?"El espacio guarda escenarios con entradas, fecha y versión del cálculo. Guardar un escenario no valida el modelo. La evaluación posterior debe usar solo datos disponibles antes de la carrera, comparar con resultados reales y separar atletas y eventos de desarrollo y evaluación.":"The workspace saves scenarios with their inputs, timestamp and calculation version. Saving a scenario does not validate the model. Later evaluation must use only information available before the race, compare against actual results and keep model-development athletes and events separate from evaluation data."}</p><p>{es?"Publicar error en minutos y porcentaje, sesgo y cobertura del intervalo por deporte, distancia y población. Mostrar tamaño de muestra, datos faltantes y fecha de validación. Comparar contra modelos simples. No prometer un porcentaje universal ni inferir una mejora de tiempo desde VFC o JStress sin validación.":"Publish error in minutes and percentage, bias and interval coverage by sport, distance and population. Show sample size, missing inputs and validation date. Compare against simple baselines. Do not promise a universal accuracy percentage or infer faster race times from HRV or JStress without validation."}</p><p>{es?"La IA debe explicar evidencia, supuestos y opciones; los cálculos y sus revisiones deben ser reproducibles. La integración futura requiere datos autorizados, procedencia y límites del proveedor, no solo más datos.":"AI should explain evidence, assumptions and options; calculations and revisions should be reproducible. Future integration needs authorized data, provenance and provider limits, not simply more data."}</p></div>
 </section>;}
