"use client";
const rows=[
 ["Running / Carrera","Threshold pace, a distance-extrapolation curve, heat, terrain and training-load adjustments.","Ritmo umbral, curva de extrapolación por distancia, calor, terreno y ajustes de carga.","Dated race results at relevant distances; long-run durability; course, surface and conditions. Sprint races need a separate model.","Resultados fechados a distancias relevantes; resistencia a la fatiga; recorrido, superficie y condiciones. La velocidad en pista necesita otro modelo."],
 ["Swimming / Natación","Reference pace multiplied by distance, with open-water, current, temperature, wetsuit and drafting assumptions.","Ritmo de referencia por distancia, con supuestos de aguas abiertas, corriente, temperatura, neopreno y drafting.","Stroke, pool length, starts/turns, dated trials and open-water experience. A pool reference does not establish an ocean-race finish time.","Estilo, longitud de piscina, salidas/virajes, pruebas fechadas y experiencia en aguas abiertas. Una referencia de piscina no determina el tiempo en el mar."],
 ["Cycling / Ciclismo","FTP-based sustainable power and a speed calculation using aerodynamic drag, mass, rolling resistance, wind and climbing.","Potencia sostenible basada en FTP y velocidad calculada con aerodinámica, masa, rodadura, viento y desnivel.","Calibrated power history, duration-specific power, fatigue resistance, rider position, equipment and course segments. Generic aerodynamic values are estimates.","Historial de potencia calibrada, potencia por duración, resistencia a la fatiga, posición, material y segmentos del recorrido. La aerodinámica genérica es estimada."],
 ["Triathlon / Triatlón","Swim, bike and run estimates plus transitions and an assumed effect of cycling work on the run.","Estimaciones de natación, bici y carrera más transiciones y un efecto supuesto del ciclismo sobre la carrera.","Evidence from all three sports; actual brick/race results; transition times; race distance, drafting rules, conditions and practiced fueling. Standalone personal bests cannot simply be added.","Evidencia de los tres deportes; resultados de sesiones combinadas/carreras; transiciones; distancia, reglas de drafting, condiciones y alimentación practicada. No basta sumar marcas individuales."],
 ["HYROX","A separate visible scenario planner combines entered running and station assumptions. Older forecast code also contains heuristic fatigue adjustments; it is disabled.","Un planificador visible separado combina supuestos introducidos de carrera y estaciones. El código antiguo también incluye ajustes supuestos de fatiga; está deshabilitado.","Division and official loads, all eight run and station splits, transitions/Roxzone, penalties, venue and repeated comparable performances. Station skill and accumulated fatigue need individual evidence.","División y cargas oficiales, ocho parciales de carrera y estaciones, transiciones/Roxzone, penalizaciones, sede y resultados comparables repetidos. Técnica y fatiga acumulada necesitan evidencia individual."]
];
export function RaceMethodology({es}:{es:boolean}){return <section className="mt-12 space-y-6" id="methodology">
 <h2 className="display-lg">{es?"Qué calcula y cuánto sabemos de su precisión":"What it calculates—and what we know about accuracy"}</h2>
 <p>{es?"La tabla describe código existente y datos necesarios para mejorarlo; no son pronósticos activos. La precisión de JMM aún no se ha medido en carreras independientes. Un rango mejor/peor basado en el clima es un escenario, no un intervalo estadístico de predicción.":"This table describes existing code and the data needed to improve it; these are not active forecasts. JMM accuracy has not been measured on independent races. A best/worst weather range is a scenario, not a statistical prediction interval."}</p>
 <div className="overflow-x-auto rounded-xl border border-ink-200"><table className="w-full text-sm text-left"><caption className="sr-only">{es?"Modelos por deporte, aún no validados":"Sport models, not yet validated"}</caption><thead className="bg-ink-900 text-paper"><tr>{(es?["Deporte","Código actual / escenario","Evidencia necesaria"]:["Sport","Current code / scenario","Evidence needed"]).map(h=><th scope="col" className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t border-ink-200 align-top" key={r[0]}><th scope="row" className="p-4 font-semibold">{r[0]}</th><td className="p-4 leading-relaxed">{r[es?2:1]}</td><td className="p-4 leading-relaxed">{r[es?4:3]}</td></tr>)}</tbody></table></div>
 <h3 className="font-bold text-xl">{es?"Investigación útil, sin apropiarnos de su precisión":"Useful research, without borrowing its accuracy"}</h3>
 <ul className="space-y-3 list-disc pl-5 text-sm leading-relaxed">
 <li>{es?"Carrera: un estudio con 82.303 maratonistas relacionó la resistencia a la fatiga con el rendimiento. Sus resultados apoyan investigar datos de duración larga; no validan JMM.":"Running: a study of 82,303 marathon runners linked durability to performance. It supports investigating long-duration evidence; it does not validate JMM."} <a className="underline" href="https://pubmed.ncbi.nlm.nih.gov/35511416/">Smyth et al., 2022</a>.</li>
 <li>{es?"Natación: la investigación de velocidad crítica específica por estilo estudia la fiabilidad de pruebas. La fiabilidad de una prueba no equivale a precisión predictiva en aguas abiertas.":"Swimming: stroke-specific critical-speed research examines test reliability. A repeatable test is not the same as an accurate open-water prediction."} <a className="underline" href="https://pmc.ncbi.nlm.nih.gov/articles/PMC10875687/">Stroke-specific critical speed, 2024</a>.</li>
 <li>{es?"Ciclismo: una validación clásica modeló potencia en carretera con parámetros medidos. No prueba que un FTP y una aerodinámica genérica predigan tu carrera.":"Cycling: a foundational validation modeled road-cycling power with measured parameters. It does not show that FTP plus generic aerodynamics predicts your race."} <a className="underline" href="https://pubmed.ncbi.nlm.nih.gov/28121252/">Martin et al., 1998</a>.</li>
 <li>{es?"Triatlón: un estudio de ocho atletas élite encontró diferencias entre predictores para pruebas con y sin drafting. No se debe extrapolar un modelo único a toda distancia y nivel.":"Triathlon: a study of eight elite athletes found differences in predictors for drafting and non-drafting events. One model should not be assumed to cover every distance and ability."} <a className="underline" href="https://pubmed.ncbi.nlm.nih.gov/12904633/">Drafted-triathlon study, 2003</a>.</li>
 <li>{es?"HYROX: un estudio de competición simulada investigó demandas y posibles determinantes del rendimiento. Esa evidencia inicial no valida nuestro total de escenarios ni una promesa individual.":"HYROX: a simulated-competition study investigated demands and possible performance determinants. This early evidence does not validate our scenario total or an individual promise."} <a className="underline" href="https://pubmed.ncbi.nlm.nih.gov/40230601/">HYROX performance study, 2025</a>.</li>
 </ul>
 <div className="card space-y-3"><h3 className="font-bold text-xl">{es?"La siguiente fase: validar antes de habilitar":"Next phase: validate before enabling"}</h3><p>{es?"Propuesta de desarrollo, todavía no implementada: guardar un pronóstico y su versión antes de la carrera; usar solo datos disponibles en ese momento; comparar después con resultados reales; separar atletas y eventos de entrenamiento y evaluación del modelo.":"Development proposal, not yet implemented: save a forecast and model version before the race; use only information available at that time; compare it with actual results afterward; keep model-development athletes and events separate from evaluation data."}</p><p>{es?"Publicar error en minutos y porcentaje, sesgo y cobertura del intervalo por deporte, distancia y población. Mostrar tamaño de muestra, datos faltantes y fecha de validación. Comparar contra modelos simples. No prometer un porcentaje universal ni inferir una mejora de tiempo desde VFC o JStress sin validación.":"Publish error in minutes and percentage, bias and interval coverage by sport, distance and population. Show sample size, missing inputs and validation date. Compare against simple baselines. Do not promise a universal accuracy percentage or infer faster race times from HRV or JStress without validation."}</p><p>{es?"La IA debe explicar evidencia, supuestos y opciones; los cálculos y sus revisiones deben ser reproducibles. La integración futura requiere datos autorizados, procedencia y límites del proveedor, no solo más datos.":"AI should explain evidence, assumptions and options; calculations and revisions should be reproducible. Future integration needs authorized data, provenance and provider limits, not simply more data."}</p></div>
 </section>;}
