/** Real HTTP + PostgreSQL acceptance. Synthetic athletes only; exact loopback guard. */
import assert from "node:assert/strict";
import { randomBytes, randomUUID, createHash } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { PrismaClient, type User } from "@prisma/client";
import bcrypt from "bcryptjs";
import { hashToken } from "../src/lib/auth";
import { dayBounds, addDaysKey, localDate } from "../src/lib/dates";

for (const key of ["DATABASE_URL", "DIRECT_URL"]) {
  const url = new URL(process.env[key] || "");
  assert.equal(url.protocol, "postgresql:"); assert.equal(url.hostname, "127.0.0.1");
  assert.equal(url.port, "55432"); assert.equal(url.pathname, "/jmm_launch_integration_test"); assert.equal(url.search, "");
}
assert.notEqual(process.env.VERCEL_ENV, "production");
const base = new URL(process.env.JMM_INTEGRATION_BASE || "http://127.0.0.1:3220");
assert.equal(base.origin, "http://127.0.0.1:3220"); assert.equal(base.pathname, "/");
const db = new PrismaClient(), created: string[] = [], results: Array<{name:string; status:"PASS"|"FAIL"; detail?:string}> = [];
const dir = ".local/jmm-conversation-integration"; mkdirSync(dir, {recursive:true});
const { start: day, key: today } = dayBounds("UTC");
const yesterday = addDaysKey(today, -1);
type Actor = User & { cookie:string };
const validAnswers = {sleep:4,soreness:2,motivation:4,energy:4,stress:2,sick:false,newPain:false,urgentSymptoms:false,availableMinutes:60};
async function request(path:string, actor?:Actor, options:{method?:string;body?:unknown;status?:number}={}) {
  const response = await fetch(new URL(path, base), {method:options.method || (options.body === undefined ? "GET" : "POST"),headers:{"Content-Type":"application/json", ...(actor ? {cookie:actor.cookie} : {})}, ...(options.body === undefined ? {} : {body:JSON.stringify(options.body)}),redirect:"manual",signal:AbortSignal.timeout(120000)});
  if (options.status !== undefined) assert.equal(response.status, options.status, `${path}: ${response.status}: ${response.status === options.status ? "" : (await response.clone().text()).slice(0,500)}`);
  return response;
}
async function json(path:string, actor?:Actor, options:Parameters<typeof request>[2]={}) {return (await request(path,actor,{status:200,...options})).json();}
async function scenario(name:string, task:()=>Promise<void>) {try {await task();results.push({name,status:"PASS"});console.log(`PASS ${name}`);} catch(e) {const detail=e instanceof Error?e.message:String(e);results.push({name,status:"FAIL",detail});console.error(`FAIL ${name}: ${detail}`);}}
async function actor(label:string, language="en"):Promise<Actor> {
  const user=await db.user.create({data:{email:`coach-${label}-${randomUUID()}@example.invalid`,name:`Synthetic conversational ${label}`,passwordHash:bcrypt.hashSync(randomBytes(24).toString("base64url"),10),role:"athlete",timezone:"UTC",language,onboarded:true,
    profile:{create:{goal:"run-only",experience:"amateur",weeklyHours:3,birthYear:1990,weightKg:70}},reminder:{create:{emailEnabled:false,telegramEnabled:false}}}});
  created.push(user.id);const token=randomBytes(32).toString("hex");await db.authSession.create({data:{userId:user.id,tokenHash:hashToken(token),expiresAt:new Date(Date.now()+3600000)}});
  const a={...user,cookie:`jmm_session=${token}`};const p=await json("/api/profile",a);
  await json("/api/profile",a,{method:"PUT",body:{expectedRevision:p.revision,expectedSetupRevision:p.setupRevision??null,experience:"amateur",weeklyHours:3,setup:{adultConfirmed:true,profileConfirmed:true,goalDescription:"Run comfortably for general fitness",baselineWeeklyMinutes:120,baselineObservedAt:today,interruptions:"none",restrictions:"none",qualifiedReview:"none_needed",trainingDays:[0,1,2,3,4,5,6],maxSessionMinutes:60,equipmentAccess:"Shoes and outdoor path",planWeeks:4}}});
  return a;
}
async function fixture(a:Actor, offset=0, historic=false) {
  const date=localDate(addDaysKey(today,offset),"UTC");
  return db.workout.create({data:{userId:a.id,date,sport:"run",title:historic?"Recorded historic run":"Reviewed easy run",type:"endurance",durationMin:30,intensity:"z2",planned:true,approved:true,source:"manual",completed:historic,
    ...(historic?{feedbackStatus:"completed",actualDurationMin:28,rpe:3,feedbackAt:new Date()}:{}),
    prescription:JSON.stringify({title:"Reviewed easy run",sport:"run",durationMin:30,intensity:"z2",type:"endurance",verdict:"full",steps:[{name:"Easy warm-up",seconds:300,zone:"z1",phase:"warmup",target:{type:"open"}},{name:"Controlled running",seconds:1200,zone:"z2",phase:"active",target:{type:"open"}},{name:"Easy finish",seconds:300,zone:"z1",phase:"cooldown",target:{type:"open"}}]})}});
}
async function ask(a:Actor,message:string,extra:Record<string,unknown>={}) {return json("/api/assistant",a,{body:{message,source:"text",externalConsent:false,clientRequestId:randomUUID(),...extra}});}
function pending(result:any) {assert.ok(result.proposal?.id,"Expected a reviewable saved proposal");assert.ok(result.proposal.candidates?.length,"Expected explicit candidates");return result.proposal;}
function confirmBody(p:any,candidates=p.candidates) {return {proposalId:p.id,expectedRevision:p.revision,candidates,idempotencyKey:randomUUID(),confirmed:true};}
async function main() {
  await scenario("Unauthenticated access and invalid envelopes fail without success",async()=>{await request("/api/assistant",undefined,{status:401});await request("/api/assistant",undefined,{body:{message:"hello"},status:401});const a=await actor("invalid");for(const body of [null,[],{message:""},{message:"x".repeat(10001)},{message:"hello",source:"web"},{message:"hello",externalConsent:"yes"},{message:"image",image:{url:"http://127.0.0.1/private"}}]) await request("/api/assistant",a,{body,status:400});});
  await scenario("Message request IDs replay once, reject changed bodies, and deduplicate concurrent sends",async()=>{const a=await actor("request-id");const clientRequestId=randomUUID();const body={message:"Why is easy endurance useful?",source:"text",externalConsent:false,clientRequestId};await json("/api/assistant",a,{body});const repeated=await json("/api/assistant",a,{body});assert.equal(repeated.replayed,true);assert.equal((await json("/api/assistant",a)).conversation.messages.length,2);await request("/api/assistant",a,{body:{...body,message:"Different question"},status:409});const parallel={...body,clientRequestId:randomUUID(),message:"What is perceived exertion?"};const responses=await Promise.all([request("/api/assistant",a,{body:parallel}),request("/api/assistant",a,{body:parallel})]);assert.ok(responses.some(r=>r.status===200));assert.ok(responses.every(r=>[200,409].includes(r.status)));assert.equal((await json("/api/assistant",a)).conversation.messages.length,4);});
  await scenario("Provider consent with unconfigured keys performs no paid extraction and preserves local state",async()=>{const a=await actor("provider-off");const result=await ask(a,"Why is easy endurance useful?",{externalConsent:true,textProviderConsent:"gemini"});assert.equal(result.externalStatus,"not_configured");assert.equal(result.trainingModified,false);const capabilities=(await json("/api/assistant",a)).capabilities;assert.equal(capabilities.externalAi,false);assert.equal(capabilities.imageUnderstanding,false);});
  await scenario("Conversation persists, remains owner-scoped, and clears only its own text",async()=>{const a=await actor("memory"),b=await actor("other");const w=await fixture(a,-1,true);await ask(a,"I want to be consistent this month.");await ask(a,"Can we keep that goal in mind?");await ask(b,"A separate athlete conversation.");const before=await json("/api/assistant",a);assert.ok(before.conversation.messages.length>=4);assert.ok(before.conversation.messages.some((m:any)=>m.content.includes("consistent")));await request(`/api/assistant?athleteId=${b.id}`,a,{status:403});await request(`/api/assistant?athleteId=${b.id}`,a,{method:"DELETE",body:{confirmed:true},status:403});await json("/api/assistant",a,{method:"DELETE",body:{confirmed:true}});assert.equal((await json("/api/assistant",a)).conversation.messages.length,0);assert.ok((await json("/api/assistant",b)).conversation.messages.length>0);assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,28);});
  await scenario("Editable explicit profile review really saves and returns idempotent receipt",async()=>{const a=await actor("profile");const p=pending(await ask(a,"My weekly availability is 5 hours per week."));assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weeklyHours,3);const selected=p.candidates.filter((c:any)=>c.kind==="profile"&&c.field==="weeklyHours").map((c:any)=>({...c,value:4}));assert.equal(selected.length,1);const body=confirmBody(p,selected);const receipt=await json("/api/assistant/confirm",a,{body});assert.equal(receipt.ok,true);assert.ok(receipt.receipt.pendingActions.includes("review_plan"));assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weeklyHours,4);await json("/api/assistant/confirm",a,{body});assert.equal(await db.auditLog.count({where:{subjectId:a.id,action:"profile.update"}}),2,"Setup save plus exactly one conversational save");assert.ok(await db.auditLog.count({where:{subjectId:a.id,action:"coach.conversation.confirmed"}})>0);const remembered=await ask(a,"What is my weekly availability?");assert.match(remembered.answer,/4.*hours|4.*horas/i);});
  await scenario("Stale profile, wrong athlete, candidate expansion and missing confirmation cannot write",async()=>{const a=await actor("stale"),b=await actor("thief");const p=pending(await ask(a,"My weekly availability is 5 hours per week."));const body=confirmBody(p);await request("/api/assistant/confirm",b,{body,status:404});await request("/api/assistant/confirm",a,{body:{...body,confirmed:false},status:400});await request("/api/assistant/confirm",a,{body:{...body,candidates:p.candidates.map((c:any)=>({...c,field:"ftp",value:400,unit:"W"}))},status:400});const profile=await json("/api/profile",a);await json("/api/profile",a,{method:"PUT",body:{expectedRevision:profile.revision,weeklyHours:6}});await request("/api/assistant/confirm",a,{body,status:409});const saved=await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}});assert.equal(saved.weeklyHours,6);assert.equal(saved.ftp,null);});
  await scenario("Superseded and timezone-changed proposals require a fresh review",async()=>{const a=await actor("superseded");const old=pending(await ask(a,"My weekly availability is 5 hours per week."));const next=pending(await ask(a,"My weekly availability is 6 hours per week."));await request("/api/assistant/confirm",a,{body:confirmBody(old),status:409});await db.user.update({where:{id:a.id},data:{timezone:"Pacific/Kiritimati"}});await request("/api/assistant/confirm",a,{body:confirmBody(next),status:409});assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weeklyHours,3);});
  await scenario("Administrator scope does not bypass the private-conversation boundary",async()=>{const a=await actor("private-owner"),admin=await actor("admin-private");await db.user.update({where:{id:admin.id},data:{role:"admin"}});await ask(a,"My private conversation context.");await request(`/api/assistant?athleteId=${a.id}`,admin,{status:403});await request(`/api/assistant?athleteId=${a.id}`,admin,{method:"DELETE",body:{confirmed:true},status:403});assert.ok((await json("/api/assistant",a)).conversation.messages.length>0);});
  await scenario("Cancellation prevents confirmation and does not claim health data was saved",async()=>{const a=await actor("cancel");const p=pending(await ask(a,"My weekly availability is 5 hours per week."));await json("/api/assistant/cancel",a,{body:{proposalId:p.id}});await request("/api/assistant/confirm",a,{body:confirmBody(p),status:409});assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weeklyHours,3);});
  await scenario("Completed activity feedback saves separately, preserves prescription, and reaches authoritative Today reassessment",async()=>{const a=await actor("journey");const w=await fixture(a),future=await fixture(a,1),historic=await fixture(a,-1,true);await json("/api/checkin",a,{body:validAnswers});const before=await db.workout.findUniqueOrThrow({where:{id:w.id}});const beforeView=(await json("/api/today",a)).sessions.find((session:any)=>session.id===w.id);const p=pending(await ask(a,"Today I completed my run for 25 minutes, RPE 4.",{sessionId:w.id}));const feedback=p.candidates.filter((c:any)=>c.kind==="workout_feedback");assert.ok(feedback.some((c:any)=>c.field==="actualDurationMin"&&c.value===25));await json("/api/assistant/confirm",a,{body:confirmBody(p,feedback)});const saved=await db.workout.findUniqueOrThrow({where:{id:w.id}});assert.equal(saved.actualDurationMin,25);assert.equal(saved.rpe,4);assert.equal(saved.completed,true);assert.equal(saved.prescription,before.prescription);const visible=(await json("/api/today",a)).sessions.find((s:any)=>s.id===w.id);assert.equal(visible.actualDurationMin,25);assert.notEqual(visible.revision,beforeView.revision);await request(`/api/workout/approve?sessionId=${w.id}&expectedRevision=${beforeView.revision}`,a,{status:409});assert.equal(await db.coachingPrompt.count({where:{userId:a.id}}),0);const remembered=await ask(a,"What was my last recorded workout?");assert.match(remembered.answer,/25.*min/i);const adaptation=await json("/api/checkin",a,{body:validAnswers});assert.equal(adaptation.ok,true);assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).prescription,before.prescription);assert.equal((await db.workout.findUniqueOrThrow({where:{id:future.id}})).prescription,future.prescription);assert.equal((await db.workout.findUniqueOrThrow({where:{id:historic.id}})).actualDurationMin,28);});
  await scenario("Mixed profile/workout review rolls back entirely if the selected workout changed",async()=>{const a=await actor("atomic"),w=await fixture(a);const p=pending(await ask(a,"My weekly availability is 5 hours per week. Today I completed my run for 25 minutes, RPE 4.",{sessionId:w.id}));assert.ok(p.candidates.some((c:any)=>c.kind==="profile"));assert.ok(p.candidates.some((c:any)=>c.kind==="workout_feedback"));await db.workout.update({where:{id:w.id},data:{title:"Concurrent externally reviewed edit"}});await request("/api/assistant/confirm",a,{body:confirmBody(p),status:409});assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weeklyHours,3);assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,null);});
  await scenario("Concurrent confirmation applies at most once and altered replay cannot reapply",async()=>{const a=await actor("concurrent");const p=pending(await ask(a,"My weekly availability is 5 hours per week."));const body=confirmBody(p);const responses=await Promise.all([request("/api/assistant/confirm",a,{body}),request("/api/assistant/confirm",a,{body})]);assert.ok(responses.some(r=>r.status===200));assert.ok(responses.every(r=>[200,409].includes(r.status)));await json("/api/assistant/confirm",a,{body});assert.equal(await db.auditLog.count({where:{subjectId:a.id,action:"coach.conversation.confirmed"}}),1);await request("/api/assistant/confirm",a,{body:{...body,candidates:body.candidates.map((c:any)=>({...c,value:6}))},status:409});assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weeklyHours,5);});
  await scenario("Clearing chat removes cancelled/superseded proposal evidence but preserves applied health audits",async()=>{const a=await actor("delete-proposals");const one=pending(await ask(a,"My weekly availability is 5 hours per week."));await json("/api/assistant/cancel",a,{body:{proposalId:one.id}});await ask(a,"My weekly availability is 6 hours per week.");const latest=pending(await ask(a,"My weight is 71 kg."));await json("/api/assistant/confirm",a,{body:confirmBody(latest)});await json("/api/assistant",a,{method:"DELETE",body:{confirmed:true}});const rows=await db.coachConversationProposal.findMany({where:{userId:a.id}});assert.ok(rows.every(r=>!r.candidates.includes("availability")));assert.equal((await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}})).weightKg,71);assert.equal(await db.auditLog.count({where:{subjectId:a.id,action:"coach.conversation.confirmed"}}),1);});
  await scenario("EN/ES voice is an editable transcript and requires explicit review before saving",async()=>{const a=await actor("voz","es"),w=await fixture(a);const p=pending(await ask(a,"Hoy completé mi carrera durante 22 minutos, RPE 3.",{source:"voice",sessionId:w.id}));assert.ok(p.candidates.every((c:any)=>c.source==="voice"));assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,null);await json("/api/assistant/confirm",a,{body:confirmBody(p)});assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,22);});
  await scenario("Session ownership, date contradictions and future completion fail closed",async()=>{const a=await actor("binding"),b=await actor("binding-other");const w=await fixture(a),other=await fixture(b);await request("/api/assistant",a,{body:{message:"Today I completed my run for 25 minutes.",sessionId:other.id},status:404});for(const message of ["Tomorrow I completed my run for 25 minutes.",`On ${yesterday} I completed my run for 25 minutes.`]){const res=await request("/api/assistant",a,{body:{message,sessionId:w.id}});assert.ok([200,400].includes(res.status));const result=await res.json();assert.ok(!result.proposal?.candidates?.some((c:any)=>c.kind==="workout_feedback"),"Contradictory completion must not be applicable");}assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,null);});
  await scenario("Goal, hypothetical and future-plan discussion never becomes measured capacity or silent rewrite",async()=>{const a=await actor("future"),future=await fixture(a,1);const aspiration=await ask(a,"My goal is a marathon in 3 hours.");assert.ok(!aspiration.proposal?.candidates?.some((c:any)=>["runPaceBase","ftp","vo2max","lthr"].includes(c.field)));const hypothetical=await ask(a,"What if I ran 50 minutes tomorrow?");assert.ok(!hypothetical.proposal?.candidates?.some((c:any)=>c.kind==="workout_feedback"));const result=await ask(a,"Tomorrow I plan to run for 40 minutes.",{sessionId:future.id});assert.equal(result.trainingModified,false);const review=pending(result);const receipt=await json("/api/assistant/confirm",a,{body:confirmBody(review)});assert.equal(receipt.applied,false);assert.equal(receipt.receipt.applied.length,0);assert.ok(receipt.receipt.pendingActions.includes("review_plan"));assert.equal((await db.workout.findUniqueOrThrow({where:{id:future.id}})).durationMin,30);});
  await scenario("Motivation advice is firm only with current safety, accepts refusal, and prioritizes danger",async()=>{const a=await actor("motivation");await fixture(a);let response=await ask(a,"I'm tired.");assert.match(response.answer,/pain|ill|fatigue|tired|check-in/i);await json("/api/checkin",a,{body:validAnswers});await db.workout.updateMany({where:{userId:a.id,date:day},data:{approved:true}});response=await ask(a,"I feel fine, no pain or illness, just can't be bothered.");assert.match(response.answer,/warm.up already|calentamiento ya previsto/i);response=await ask(a,"I am lazy and my chest hurts.");assert.match(response.answer,/stop|urgent|emergency/i);assert.doesNotMatch(response.answer,/start.*warm.up|push through/i);response=await ask(a,"Stop pushing; I choose rest.");assert.doesNotMatch(response.answer,/start.*warm.up|push through/i);});
  await scenario("Images require valid bounded inline bytes and explicit consent, no arbitrary fetch",async()=>{const a=await actor("image");for(const image of [{mimeType:"image/svg+xml",dataBase64:Buffer.from("<svg/>").toString("base64")},{mimeType:"image/png",dataBase64:"not_base64"},{mimeType:"image/png",dataBase64:Buffer.from("not an image").toString("base64")},{mimeType:"image/png",url:"https://example.invalid/private"}]) await request("/api/assistant",a,{body:{message:"Review screenshot",externalConsent:true,image},status:400});const pixel="iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADklEQVQImWM4AQYMEAoAQa4JYfTnnZUAAAAASUVORK5CYII=";const result=await ask(a,"Here is a screenshot.",{image:{mimeType:"image/png",dataBase64:pixel}});assert.equal(result.trainingModified,false);assert.ok(!result.proposal?.candidates?.length);assert.match(JSON.stringify(result),/consent|not_requested|not_configured|unavailable|describe/i);});
}
main().catch(e=>{results.push({name:"Runner setup",status:"FAIL",detail:String(e)});console.error(e);}).finally(async()=>{
  let cleanup=false;try {await db.usageCounter.deleteMany({where:{userId:{in:created}}});await db.appEvent.deleteMany({where:{userId:{in:created}}});await db.user.deleteMany({where:{id:{in:created}}});assert.equal(await db.user.count({where:{id:{in:created}}}),0);cleanup=true;}catch(e){results.push({name:"Fixture cleanup",status:"FAIL",detail:String(e)});}await db.$disconnect();
  let commit="unknown",sourceFingerprint:string|null=null;try{commit=execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();const paths=execFileSync("git",["ls-files","--cached","--others","--exclude-standard"],{encoding:"utf8"}).trim().split("\n").filter(p=>/^(src\/|scripts\/|prisma\/|package(?:-lock)?\.json$)/.test(p)).sort();const hash=createHash("sha256");for(const p of paths)hash.update(p).update("\0").update(readFileSync(p));sourceFingerprint=hash.digest("hex");}catch{}
  writeFileSync(`${dir}/report.json`,JSON.stringify({generatedAt:new Date().toISOString(),commit,sourceFingerprint,appMode:process.env.JMM_TEST_APP_MODE,environment:"Disposable loopback PostgreSQL and synthetic athletes; no external requests",results,cleanup:{createdUsers:created.length,verified:cleanup},notRun:["Live external AI/image extraction","Real athlete data or device delivery","Production migration/deployment","Real browser voice permissions"]},null,2));const failed=results.filter(r=>r.status==="FAIL");console.log(`${results.length-failed.length}/${results.length} conversation acceptance scenarios passed.`);if(failed.length)process.exitCode=1;
});
