import { hashToken as hashSessionToken } from "../src/lib/auth";
import bcrypt from "bcryptjs";
/**
 * Dedicated followup acceptance: synthetic accounts, private loopback database,
 * mock communication only, independently decoded FIT. Never use production data.
 * Start through jmm-followup-local-run.sh; see its hard-coded safety boundaries.
 */
import assert from "node:assert/strict";
import { randomBytes, randomUUID, createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, rmSync, readdirSync } from "node:fs";
import { PrismaClient, type User } from "@prisma/client";
import { Decoder, Stream } from "@garmin/fitsdk";
import { dayBounds } from "../src/lib/dates";
import { isDailyTraining } from "../src/components/daily-training/training-contract";

for(const name of ["DATABASE_URL","DIRECT_URL"]) {
  const u=new URL(process.env[name]||""); assert.equal(u.protocol,"postgresql:"); assert.equal(u.hostname,"127.0.0.1");assert.equal(u.port,"55432");assert.equal(u.pathname,"/jmm_launch_integration_test");assert.equal(u.search,"");
}
assert.notEqual(process.env.VERCEL_ENV,"production");
assert.equal(process.env.ENABLE_MOCK_COACHING,"true");assert.equal(process.env.COACHING_TRANSPORT,"mock");
const base="http://127.0.0.1:3220",db=new PrismaClient(),created:string[]=[];
const day=dayBounds("UTC").start, date=day.toISOString().slice(0,10);
const results:{name:string;status:"PASS"|"FAIL";detail?:string}[]=[],artifacts:Record<string,unknown>[]=[];
const dir=".local/jmm-followup-integration";mkdirSync(dir,{recursive:true});
for(const f of readdirSync(dir)) if(/\.(fit|json|zip)$/.test(f))rmSync(`${dir}/${f}`,{force:true});
type Actor=User&{cookie:string};
async function request(path:string,who?:Actor,options:{body?:unknown;method?:string;status?:number}={}) {
  const res=await fetch(base+path,{method:options.method||(options.body===undefined?"GET":"POST"),headers:{"Content-Type":"application/json",...(who?{cookie:who.cookie}:{})},...(options.body===undefined?{}:{body:JSON.stringify(options.body)}),redirect:"manual",signal:AbortSignal.timeout(120000)});
  if(options.status!==undefined&&res.status!==options.status)throw Error(`${options.method||(options.body===undefined?"GET":"POST")} ${path}: expected ${options.status}, received ${res.status}: ${(await res.text()).slice(0,700)}`);return res;
}
async function json(path:string,who?:Actor,options:Parameters<typeof request>[2]={}) { return (await request(path,who,{status:200,...options})).json(); }
async function scenario(name:string,run:()=>Promise<void>) {try{await run();results.push({name,status:"PASS"});console.log(`PASS ${name}`);}catch(e){const detail=e instanceof Error?e.message:String(e);results.push({name,status:"FAIL",detail});console.error(`FAIL ${name}: ${detail}`);}}
async function actor(label:string):Promise<Actor> {
  const u=await db.user.create({data:{email:`followup-${label}-${randomUUID()}@example.invalid`,name:`Synthetic followup ${label}`,passwordHash:bcrypt.hashSync(randomBytes(32).toString("hex"),4),timezone:"UTC",language:"en",onboarded:true,profile:{create:{birthYear:1990,goal:"run-only",experience:"amateur",weeklyHours:3}},reminder:{create:{emailEnabled:false,telegramEnabled:false}}}});created.push(u.id);
  const token=randomBytes(32).toString("hex");await db.authSession.create({data:{userId:u.id,tokenHash:hashSessionToken(token),expiresAt:new Date(Date.now()+7200000)}});
  const a={...u,cookie:`jmm_session=${token}`};await setup(a);await clearCheckin(a);return a;
}
const baseSetup={adultConfirmed:true,profileConfirmed:true,goalDescription:"Train comfortably for general fitness",baselineWeeklyMinutes:120,baselineObservedAt:date,interruptions:"none",restrictions:"none",qualifiedReview:"none_needed",trainingDays:[day.getUTCDay(),(day.getUTCDay()+2)%7,(day.getUTCDay()+4)%7],maxSessionMinutes:60,equipmentAccess:"Running shoes, stationary bike, pool and exercise space",planWeeks:4};
async function setup(a:Actor,patch:Record<string,unknown>={}) {const p=await json("/api/profile",a);return json("/api/profile",a,{method:"PUT",body:{expectedRevision:p.revision,expectedSetupRevision:p.setupRevision??null,goal:"run-only",experience:"amateur",weeklyHours:3,birthYear:1990,setup:{...baseSetup,...patch}}});}
async function clearCheckin(a:Actor){const answers=JSON.stringify({sleep:4,soreness:2,motivation:4,energy:4,stress:2,sick:false,newPain:false,urgentSymptoms:false,availableMin:120,inputMetadata:{version:"checkin-safety-v1",source:"athlete-reported",observedOn:date,recordedAt:new Date().toISOString()}});const adaptation=JSON.stringify({verdict:"full",durationFactor:1,intensityCap:"z7",safetyStatus:"clear",message:"Synthetic explicit safety answers"});await db.dailyCheckin.upsert({where:{userId_date:{userId:a.id,date:day}},create:{userId:a.id,date:day,answers,adaptation},update:{answers,adaptation}});}
function step(name:string,seconds:number,phase="active"){return{name,phase,zone:"z2",seconds,endpoint:{type:"time",seconds},target:{type:"open"}};}
async function workout(a:Actor,sport="run",sportStructure?:unknown){const p={title:`Synthetic ${sport} explicit fixture`,sport,durationMin:20,intensity:"z2",verdict:"full",type:"endurance",steps:[step("Gentle start",300,"warmup"),step("Steady work",600),step("Ease off",300,"cooldown")],...(sportStructure?{sportStructure}:{})};return db.workout.create({data:{userId:a.id,date:day,sport,title:p.title,type:"endurance",durationMin:20,intensity:"z2",planned:true,source:"plan",prescription:JSON.stringify(p)}});}
async function current(a:Actor,id:string){const t=await json("/api/today",a);const s=t.sessions.find((x:any)=>x.id===id);assert.ok(s,`Selected session ${id} visible`);return s;}
async function download(a:Actor,id:string,revision?:string,status=200){return request(`/api/workout/approve?sessionId=${id}${revision?`&expectedRevision=${revision}`:""}`,a,{status});}
function decode(bytes:Buffer){const d=new Decoder(Stream.fromByteArray(new Uint8Array(bytes)));assert.equal(d.isFIT(),true);assert.equal(d.checkIntegrity(),true);const o=d.read();assert.deepEqual(o.errors,[]);assert.ok(o.messages.fileIdMesgs?.length);assert.ok(o.messages.workoutMesgs?.length);assert.ok(o.messages.workoutStepMesgs?.length);assert.equal(o.messages.fileIdMesgs[0].type,"workout");const w:any=o.messages.workoutMesgs[0],s:any[]=o.messages.workoutStepMesgs;assert.equal(w.numValidSteps,s.length);assert.deepEqual(s.map((x:any)=>x.messageIndex),s.map((_:any,i:number)=>i));return{workout:w,steps:s};}
function storedZip(bytes:Buffer){const entries=new Map<string,Buffer>();for(let o=0;o+30<=bytes.length&&bytes.readUInt32LE(o)===0x04034b50;){assert.equal(bytes.readUInt16LE(o+8),0);const size=bytes.readUInt32LE(o+18),n=bytes.readUInt16LE(o+26),extra=bytes.readUInt16LE(o+28),name=bytes.subarray(o+30,o+30+n).toString(),start=o+30+n+extra;assert.ok(!entries.has(name));entries.set(name,bytes.subarray(start,start+size));o=start+size;}assert.ok(entries.size);return entries;}
async function artifact(a:Actor,w:{id:string},name:string){const c=await current(a,w.id),daily=await json(`/api/v1/training/today?sessionId=${w.id}`,a);assert.equal(isDailyTraining(daily),true);assert.equal(daily.session.sourceRevision,c.revision);assert.deepEqual(daily.blocks.flatMap((b:any)=>b.segments).map((s:any)=>s.endpoint),c.prescription.steps.map((s:any)=>s.endpoint));assert.equal(daily.session.sport,c.sport);const r=await download(a,w.id,c.revision),bytes=Buffer.from(await r.arrayBuffer()),decoded=decode(bytes);writeFileSync(`${dir}/${name}.fit`,bytes);writeFileSync(`${dir}/${name}-decoded.json`,JSON.stringify(decoded,null,2));artifacts.push({name,revision:c.revision,...decoded});return{c,r,bytes,...decoded};}
const pool=(unit="m",sendOff=false)=>({schemaVersion:1,kind:"pool",poolLength:{value:25,unit},steps:[{kind:"lengths",name:"Easy freestyle",phase:"warmup",zone:"z1",lengths:4,stroke:"freestyle",estimatedSeconds:150},{kind:"rest",seconds:30},{kind:"lengths",name:"Controlled backstroke",phase:"active",zone:"z2",lengths:2,stroke:"backstroke",estimatedSeconds:100,...(sendOff?{sendOffSeconds:120}:{})}]});
const strength={schemaVersion:1,kind:"strength",steps:[{kind:"step",name:"Warm up",phase:"warmup",zone:"z1",endpoint:{type:"time",seconds:60}},{kind:"set",exerciseId:"squat",exerciseName:"Goblet squat",setNumber:1,zone:"z2",endpoint:{type:"reps",reps:5},load:{value:16,unit:"kg"},estimatedSeconds:30},{kind:"rest",seconds:90},{kind:"set",exerciseId:"squat",exerciseName:"Goblet squat",setNumber:2,zone:"z2",endpoint:{type:"reps",reps:5},load:{value:16,unit:"kg"},estimatedSeconds:30}]};
const brick={schemaVersion:1,kind:"brick",components:[{id:"ride",title:"Ride first",sport:"bike",durationMin:10,steps:[step("Ride easy",600)]},{id:"run",title:"Run second",sport:"run",durationMin:5,steps:[step("Run easy",300)]}],transitions:[{afterComponentId:"ride",instruction:"Rack bicycle, change shoes, then start the run file",endpoint:{type:"lap"}}]};
async function main(){
 const a=await actor("primary"),b=await actor("other");
 await scenario("New endpoints require authentication and athlete isolation",async()=>{for(const p of ["/api/target-progress","/api/coaching/preferences","/api/coaching/prompts","/api/workout/structure?id=missing"])await request(p,undefined,{status:401});await request(`/api/target-progress?athleteId=${a.id}`,b,{status:403});});
 await scenario("Numeric goal blocks planning until explicit baseline-only opt-in; anchors remain absent",async()=>{const targetGoal={metric:"pace",sport:"run",value:240,unit:"sec/km",context:"run5k"};await setup(a,{targetGoal});let v=await json("/api/target-progress",a);assert.equal(v.planningReadiness.ready,false);assert.equal(v.progress.benchmark,null);await json("/api/plan/generate",a,{status:422,body:{distance:"run-only",weeks:4,preview:true}});await setup(a,{targetGoal,baselinePlanOptIn:true});v=await json("/api/target-progress",a);assert.equal(v.planningReadiness.ready,true);assert.equal(v.planningReadiness.planningBasis,"baseline_only");const preview=await json("/api/plan/generate",a,{body:{distance:"run-only",weeks:4,preview:true}});assert.ok(preview.previewToken);const p=await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}});assert.equal(p.runPaceBase,null);assert.equal(p.ftp,null);assert.equal(await db.trainingPlan.count({where:{userId:a.id}}),0);});
 await scenario("Reported goal progress is source-labeled, revision-gated and never changes capacity or training",async()=>{const s=await json("/api/target-progress",a),profile=await db.athleteProfile.findUnique({where:{userId:a.id}}),benchmarks=await db.benchmarkTest.count({where:{userId:a.id}});const body={expectedRevision:s.revision,expectedSetupRevision:s.setupRevision,value:5,unit:"min/km",observedAt:date,contextConfirmed:true};const r=await json("/api/target-progress",a,{status:201,body});assert.ok(r.id);const v=await json("/api/target-progress",a);assert.equal(v.progress.reported.currentValue,300);assert.equal(v.progress.reported.observation.source,"athlete_reported");assert.equal(v.progress.benchmark,null);assert.deepEqual(await db.athleteProfile.findUnique({where:{userId:a.id}}),profile);assert.equal(await db.benchmarkTest.count({where:{userId:a.id}}),benchmarks);await request("/api/target-progress",a,{status:409,body});await request("/api/target-progress",b,{status:409,body});});
 await scenario("Measurement correction preserves historical observation; cross-athlete correction rejects",async()=>{let s=await json("/api/target-progress",a);const original=s.progress.reported.observation.id;await json("/api/target-progress",a,{status:201,body:{expectedRevision:s.revision,expectedSetupRevision:s.setupRevision,value:4.5,unit:"min/km",observedAt:date,contextConfirmed:true,supersedesId:original,note:"Corrected synthetic transcription"}});s=await json("/api/target-progress",a);assert.equal(s.progress.reported.currentValue,270);assert.ok(await db.auditLog.findUnique({where:{id:original}}));await setup(b,{targetGoal:{metric:"pace",sport:"run",value:240,unit:"sec/km",context:"run5k"},baselinePlanOptIn:true});const other=await json("/api/target-progress",b);await request("/api/target-progress",b,{status:404,body:{expectedRevision:other.revision,expectedSetupRevision:other.setupRevision,value:4,unit:"min/km",observedAt:date,contextConfirmed:true,supersedesId:original,note:"Must not correct another athlete"}});});
 await scenario("Concurrent measurement submission allows one revision-bound immutable report",async()=>{const s=await json("/api/target-progress",a),before=await db.auditLog.count({where:{subjectId:a.id,action:"target.measurement"}}),body={expectedRevision:s.revision,expectedSetupRevision:s.setupRevision,value:4.7,unit:"min/km",observedAt:date,contextConfirmed:true};const responses=await Promise.all([request("/api/target-progress",a,{body}),request("/api/target-progress",a,{body})]);assert.deepEqual(responses.map(x=>x.status).sort(),[201,409]);assert.equal(await db.auditLog.count({where:{subjectId:a.id,action:"target.measurement"}}),before+1);});
 await scenario("Metre pool FIT decodes exact lengths, stroke, fixed rest and distinct estimates",async()=>{const a=await actor("pool-metres");const w=await workout(a,"swim",pool());const x=await artifact(a,w,"pool-metres");assert.equal(x.workout.sport,"swimming");assert.equal(x.workout.subSport,"lapSwimming");assert.equal(x.workout.poolLength,25);assert.equal(x.workout.poolLengthUnit,"metric");assert.deepEqual(x.steps.map((s:any)=>[s.durationType,s.durationValue]),[["distance",10000],["time",30000],["distance",5000]]);assert.equal(x.steps[0].targetType,"swimStroke");assert.equal(x.steps[2].targetType,"swimStroke");assert.notEqual(x.steps[0].targetValue,x.steps[2].targetValue);assert.equal(x.c.durationIsEstimate,true);});
 await scenario("Yard pool preserves 25 yd as 22.86 m without silently changing display unit",async()=>{const a=await actor("pool-yards");const w=await workout(a,"swim",pool("yd"));const x=await artifact(a,w,"pool-yards");assert.equal(x.workout.poolLength,22.86);assert.equal(x.workout.poolLengthUnit,"statute");assert.equal(x.steps[0].durationValue,9144);assert.equal(x.steps[2].durationValue,4572);assert.match(JSON.stringify(x.c),/yd/);});
 await scenario("Send-off and missing/legacy/open-water pool structure refuse misleading native FIT",async()=>{const a=await actor("pool-unavailable");for(const structure of [pool("m",true),undefined,{schemaVersion:1,kind:"openWater",steps:[step("Swim by effort",1200)]}]){const w=await workout(a,"swim",structure);await download(a,w.id,undefined,422);}});
 await scenario("Strength companion preserves sets, reps, loads and rests with honest lap endpoints",async()=>{const a=await actor("strength-isolated");const w=await workout(a,"strength",strength);const x=await artifact(a,w,"strength-companion");assert.equal(x.workout.sport,"generic");assert.deepEqual(x.steps.map((s:any)=>s.durationType),["time","open","time","open"]);assert.deepEqual(x.steps.map((s:any)=>s.durationValue),[60000,0,90000,0]);assert.match(x.steps[1].notes,/5/);assert.match(x.steps[1].notes,/16 kg/);assert.match(x.steps[1].notes,/set 1/);assert.match(x.steps[3].notes,/set 2/);assert.match(JSON.stringify(x.c),/generic|companion/i);});
 await scenario("Brick download contains ordered distinct component files and explicit transition manifest",async()=>{const a=await actor("brick-isolated");const w=await workout(a,"brick",brick);const c=await current(a,w.id),r=await download(a,w.id,c.revision);assert.match(r.headers.get("content-type")||"",/zip/);const bytes=Buffer.from(await r.arrayBuffer());writeFileSync(`${dir}/brick-ordered.zip`,bytes);const entries=storedZip(bytes),fits=[...entries].filter(([n])=>n.endsWith(".fit"));assert.equal(fits.length,2);assert.equal(decode(fits[0][1]).workout.sport,"cycling");assert.equal(decode(fits[1][1]).workout.sport,"running");assert.notEqual(decode(fits[0][1]).workout.wktName.slice(0,15),decode(fits[1][1]).workout.wktName.slice(0,15));const manifest=entries.get("transition-manifest.json");assert.ok(manifest);const parsed=JSON.parse(manifest.toString());assert.match(JSON.stringify(parsed),/Rack bicycle/);assert.match(JSON.stringify(parsed),/ride/);assert.match(JSON.stringify(parsed),/run/);writeFileSync(`${dir}/brick-manifest.json`,JSON.stringify(parsed,null,2));artifacts.push({name:"brick",files:fits.map(([name])=>name),manifest:parsed});});
 await scenario("Sport editor validates JSON, tenant/revision ownership, historical immutability and clear safety",async()=>{const a=await actor("editor-isolated");const w=await workout(a,"swim");await request(`/api/workout/structure?id=${w.id}`,b,{status:404});let s=await json(`/api/workout/structure?id=${w.id}`,a);await request("/api/workout/structure",a,{method:"PATCH",status:409,body:{id:w.id,expectedRevision:"0".repeat(64),sportStructure:pool()}});await json("/api/workout/structure",a,{method:"PATCH",body:{id:w.id,expectedRevision:s.revision,sportStructure:pool()}});s=await json(`/api/workout/structure?id=${w.id}`,a);assert.equal(s.sportStructure.kind,"pool");await download(a,w.id,s.revision);await json("/api/workout/structure",a,{method:"PATCH",body:{id:w.id,expectedRevision:s.revision,sportStructure:null}});const after=await db.workout.findUniqueOrThrow({where:{id:w.id}});assert.deepEqual(JSON.parse(after.prescription!).steps,[]);await download(a,w.id,undefined,409);const completed=await workout(a,"strength",strength);await db.workout.update({where:{id:completed.id},data:{completed:true,feedbackStatus:"completed",feedbackAt:new Date()}});s=await json(`/api/workout/structure?id=${completed.id}`,a);await request("/api/workout/structure",a,{method:"PATCH",status:409,body:{id:completed.id,expectedRevision:s.revision,sportStructure:strength}});});
 await scenario("Baseline-only planning is unchanged by aspirational target pace and cannot substitute goal for evidence",async()=>{const a=await actor("goal-equivalence"),goal={metric:"pace",sport:"run",value:240,unit:"sec/km",context:"run5k"};await setup(a,{targetGoal:goal,baselinePlanOptIn:true});const fast=await json("/api/plan/generate",a,{body:{distance:"run-only",weeks:4,preview:true}});await setup(a,{targetGoal:{...goal,value:600},baselinePlanOptIn:true});await request("/api/plan/generate",a,{status:409,body:{distance:"run-only",weeks:4,previewToken:fast.previewToken}});const slow=await json("/api/plan/generate",a,{body:{distance:"run-only",weeks:4,preview:true}});assert.deepEqual(slow.preview.weeksPreview,fast.preview.weeksPreview);assert.equal(slow.planningBasis,"baseline_only");await json("/api/plan/generate",a,{body:{distance:"run-only",weeks:4,previewToken:slow.previewToken}});assert.equal(await db.trainingPlan.count({where:{userId:a.id,status:"active"}}),1);const p=await db.athleteProfile.findUniqueOrThrow({where:{userId:a.id}});assert.equal(p.runPaceBase,null);assert.equal(p.ftp,null);});
 await scenario("Explicit pool/strength/brick structures survive clear check-in; reduction holds instead of invented resizing",async()=>{
  // Independent encoding samples are separate athletes, not an unreviewed
  // multi-demanding day. Combined-load behavior has its own safety acceptance.
  for(const [sport,structure]of [["swim",pool()],["strength",strength],["brick",brick]] as const){
    const a=await actor(`structure-retention-${sport}`),w=await workout(a,sport,structure);
    const answers={sleep:4,soreness:2,motivation:4,energy:4,stress:2,sick:false,newPain:false,urgentSymptoms:false,availableMinutes:120};
    await json("/api/checkin",a,{body:answers});
    assert.deepEqual(JSON.parse((await db.workout.findUniqueOrThrow({where:{id:w.id}})).prescription!).sportStructure,structure);await download(a,w.id);
    await json("/api/checkin",a,{body:{...answers,availableMinutes:5}});
    assert.deepEqual(JSON.parse((await db.workout.findUniqueOrThrow({where:{id:w.id}})).prescription!).sportStructure,structure);await download(a,w.id,undefined,409);
  }
 });
 await scenario("Single and complete-bundle exports agree for brick components and current safety holds",async()=>{const a=await actor("brick-bundle"),w=await workout(a,"brick",brick);const plan=await db.trainingPlan.create({data:{userId:a.id,name:"Synthetic brick bundle plan",distance:"run-only",level:"amateur",weeks:4,startDate:day}});const planDay=await db.planDay.create({data:{planId:plan.id,date:day,week:1,dayOfWeek:day.getUTCDay(),focus:"brick"}});await db.workout.update({where:{id:w.id},data:{planDayId:planDay.id}});const single=storedZip(Buffer.from(await(await download(a,w.id)).arrayBuffer())),bundle=storedZip(Buffer.from(await(await request("/api/training/export",a,{status:200})).arrayBuffer()));const bundleFits=[...bundle].filter(([name])=>name.endsWith(".fit"));assert.equal(bundleFits.length,2);assert.deepEqual(bundleFits.map(([,bytes])=>decode(bytes).workout.sport),["cycling","running"]);for(const[name,bytes]of single)if(name.endsWith(".fit")){const match=bundleFits.find(([n])=>n.endsWith(name));assert.ok(match);assert.deepEqual(decode(match[1]),decode(bytes));}assert.ok([...bundle.keys()].some(n=>n.endsWith("transition-manifest.json")));await db.athleteProfile.update({where:{userId:a.id},data:{injured:true}});await download(a,w.id,undefined,409);const held=storedZip(Buffer.from(await(await request("/api/training/export",a,{status:200})).arrayBuffer()));assert.equal([...held.keys()].filter(n=>n.endsWith(".fit")).length,0);assert.match(held.get("fit-export-status.csv")!.toString(),new RegExp(w.id));});
 await communicationScenarios(a,b);
 await scenario("Updated pages expose truthful authenticated SSR controls",async()=>{for(const route of ["/today","/training","/connectors"]){const r=await request(route,a,{status:200});const html=await r.text();assert.ok(html.length>500);assert.ok(!/Workouts[^<]{0,20}Import/.test(html));}});
 await scenario("Zero provider network attempts and no connector side effects",async()=>{assert.equal(await db.connector.count({where:{userId:{in:created}}}),0);const attempts=readFileSync(process.env.JMM_EGRESS_LOG!,"utf8").trim().split("\n").filter(Boolean).map(x=>JSON.parse(x));assert.deepEqual(attempts.filter(x=>x.host!=="registry.npmjs.org"),[]);});
}
function prefs(channel="app") {
  const min=new Date().getUTCHours()*60+new Date().getUTCMinutes();
  return {primaryChannel:channel,paused:false,dailyPlan:true,sessionFeedback:true,missingData:true,timezone:"UTC",minuteOfDay:min,quietStart:(min+5)%1440,quietEnd:(min+6)%1440,declinedOptional:[],consentVersion:"mock-coaching-v1"};
}
async function appCoach(label:string){const a=await actor(label);await json("/api/coaching/preferences",a,{method:"PUT",body:prefs()});return a;}
function reply(p:any,actorId:string,chatId=actorId,text="status=partial; minutes=12; rpe=4; sport=run") {return{promptId:p.prompt.id,sessionId:p.prompt.sessionId,observationDate:p.prompt.observationDate,sourceRevision:p.prompt.sourceRevision,timezone:p.prompt.timezone,token:p.replyToken,actorId,chatId,text};}
async function communicationScenarios(_a:Actor,b:Actor) {
 await scenario("Communication defaults are off; opt-in requires bounded purpose consent and verified selected channel",async()=>{const a=await actor("communication-defaults"),w=await workout(a);const initial=await json("/api/coaching/preferences",a);assert.equal(initial.preferences.paused,true);assert.equal(initial.preferences.missingData,false);assert.equal(initial.externalDeliveryEnabled,false);await request("/api/coaching/telegram/webhook",undefined,{status:503,body:{}});await request("/api/coaching/prompts",a,{status:409,body:{sessionId:w.id,purpose:"missingData"}});await request("/api/coaching/preferences",a,{method:"PUT",status:400,body:{...prefs(),consentVersion:""}});await request("/api/coaching/preferences",a,{method:"PUT",status:409,body:prefs("telegram")});await request(`/api/coaching/preferences?athleteId=${a.id}`,b,{status:403});});
 await scenario("Synthetic Telegram binding is private, account-bound and one-use; no real verification claim",async()=>{const a=await actor("telegram"),p=await json("/api/coaching/pairing",a,{body:{}});assert.equal(p.transport,"mock");assert.match(p.warning,/not|No /);const bind={token:p.token,channel:"telegram",actorId:"900000000001",chatId:"900000000001",chatType:"private"};await request("/api/coaching/pairing",b,{method:"PUT",status:409,body:bind});await request("/api/coaching/pairing",a,{method:"PUT",status:400,body:{...bind,chatType:"group"}});const paired=await json("/api/coaching/pairing",a,{method:"PUT",body:bind});assert.equal(paired.verified,"synthetic-only");await request("/api/coaching/pairing",a,{method:"PUT",status:409,body:bind});await json("/api/coaching/preferences",a,{method:"PUT",body:prefs("telegram")});const w=await workout(a),prompt=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"sessionFeedback"}});assert.equal(prompt.prompt.channel,"telegram");assert.equal(prompt.prompt.status,"simulated");assert.equal(prompt.prompt.externallySent,false);assert.equal(prompt.prompt.readAt,null);assert.equal(prompt.prompt.tokenHash,undefined);const bad=reply(prompt,"900000000002");await request("/api/coaching/replies",a,{status:409,body:bad});const before=await db.workout.findUnique({where:{id:w.id}});const accepted=await json("/api/coaching/replies",a,{body:reply(prompt,bind.actorId)});assert.equal(accepted.applied,false);assert.equal(accepted.requiresConfirmation,true);assert.deepEqual(await db.workout.findUnique({where:{id:w.id}}),before);});
 await scenario("Mock reply checks athlete/session/date/timezone/revision/token and cannot mutate before app confirmation",async()=>{const a=await appCoach("reply-bindings"),w=await workout(a),p=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"sessionFeedback"}}),body=reply(p,a.id);const before=await db.workout.findUnique({where:{id:w.id}});await request("/api/coaching/replies",b,{status:404,body});for(const key of ["sessionId","observationDate","timezone","sourceRevision","token","actorId","chatId"])await request("/api/coaching/replies",a,{status:409,body:{...body,[key]:"wrong"}});await request("/api/coaching/replies",a,{status:400,body:{...body,text:"5"}});assert.deepEqual(await db.workout.findUnique({where:{id:w.id}}),before);const received=await json("/api/coaching/replies",a,{body});assert.equal(received.applied,false);assert.deepEqual(await db.workout.findUnique({where:{id:w.id}}),before);await request("/api/coaching/replies",a,{status:409,body});await request("/api/coaching/replies",b,{method:"PUT",status:404,body:{promptId:p.prompt.id,action:"confirm",expectedRevision:p.prompt.sourceRevision,candidate:received.candidate}});const confirmed=await json("/api/coaching/replies",a,{method:"PUT",body:{promptId:p.prompt.id,action:"confirm",expectedRevision:p.prompt.sourceRevision,candidate:{...received.candidate,minutes:14}}});assert.equal(confirmed.applied,true);const after=await db.workout.findUniqueOrThrow({where:{id:w.id}});assert.equal(after.actualDurationMin,14);assert.equal(after.rpe,4);assert.equal(after.completed,false);assert.equal(after.feedbackStatus,"partial");await request("/api/coaching/replies",a,{method:"PUT",status:409,body:{promptId:p.prompt.id,action:"confirm",expectedRevision:p.prompt.sourceRevision,candidate:received.candidate}});});
 await scenario("Unknown confirmed actuals remain unknown; optional declines suppress future prompts",async()=>{const a=await appCoach("unknown-actuals"),w=await workout(a),p=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"sessionFeedback"}});const received=await json("/api/coaching/replies",a,{body:reply(p,a.id,a.id,"status=unknown; minutes=unknown; rpe=unknown; sport=unknown; decline=runBenchmark")});await json("/api/coaching/replies",a,{method:"PUT",body:{promptId:p.prompt.id,action:"confirm",expectedRevision:p.prompt.sourceRevision,candidate:received.candidate}});const after=await db.workout.findUniqueOrThrow({where:{id:w.id}});assert.equal(after.actualDurationMin,null);assert.equal(after.rpe,null);assert.equal(after.completed,false);assert.equal(after.feedbackStatus,"unknown");const other=await workout(a);const next=await json("/api/coaching/prompts",a,{status:422,body:{sessionId:other.id,purpose:"missingData"}});assert.match(next.error,/No missing decision inputs/);assert.equal(await db.coachingPrompt.count({where:{userId:a.id}}),1);assert.ok((await json("/api/coaching/preferences",a)).preferences.declinedOptional.includes("runBenchmark"));});
 await scenario("Pending replies fail closed after same-length edit, expired token, pause and stale app revision",async()=>{const a=await appCoach("stale-replies"),w=await workout(a),p=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"sessionFeedback"}});await db.coachingPrompt.update({where:{id:p.prompt.id},data:{tokenExpiresAt:new Date(Date.now()-1)}});await request("/api/coaching/replies",a,{status:409,body:reply(p,a.id)});const w2=await workout(a),p2=await json("/api/coaching/prompts",a,{body:{sessionId:w2.id,purpose:"sessionFeedback"}});const received=await json("/api/coaching/replies",a,{body:reply(p2,a.id)});const prescription=JSON.parse(w2.prescription!);prescription.steps[1].name="Steady task";assert.equal(prescription.steps[1].name.length,"Steady work".length);await db.workout.update({where:{id:w2.id},data:{prescription:JSON.stringify(prescription)}});await request("/api/coaching/replies",a,{method:"PUT",status:409,body:{promptId:p2.prompt.id,action:"confirm",expectedRevision:p2.prompt.sourceRevision,candidate:received.candidate}});assert.equal((await db.workout.findUniqueOrThrow({where:{id:w2.id}})).feedbackStatus,null);await json("/api/coaching/preferences",a,{method:"PUT",body:{...prefs(),paused:true}});await request("/api/coaching/replies",a,{method:"PUT",status:409,body:{promptId:p2.prompt.id,action:"confirm",expectedRevision:p2.prompt.sourceRevision,candidate:received.candidate}});await request("/api/coaching/prompts",a,{status:409,body:{sessionId:w2.id,purpose:"dailyPlan"}});});
 await scenario("Duplicate requests are idempotent; unknown outcomes are not resent; definite failure retries are bounded",async()=>{const a=await appCoach("delivery-status"),w=await workout(a);const body={sessionId:w.id,purpose:"dailyPlan"};const one=await json("/api/coaching/prompts",a,{body});const duplicate=await json("/api/coaching/prompts",a,{body});assert.equal(duplicate.duplicate,true);assert.equal(duplicate.prompt.id,one.prompt.id);assert.equal(duplicate.prompt.attempts,1);const w2=await workout(a),unknown=await json("/api/coaching/prompts",a,{body:{sessionId:w2.id,purpose:"dailyPlan",mockOutcome:"unknown"}});const held=await json("/api/coaching/prompts",a,{body:{sessionId:w2.id,purpose:"dailyPlan"}});assert.equal(held.prompt.status,"unknown");assert.equal(held.prompt.attempts,1);assert.equal(held.replyToken,null);assert.equal(unknown.prompt.receiptId,null);const w3=await workout(a),failed=await json("/api/coaching/prompts",a,{body:{sessionId:w3.id,purpose:"dailyPlan",mockOutcome:"failed"}});assert.equal(failed.prompt.status,"failed");await request("/api/coaching/prompts",a,{status:409,body:{sessionId:w3.id,purpose:"dailyPlan"}});await db.coachingPrompt.update({where:{id:failed.prompt.id},data:{nextAttemptAt:new Date(Date.now()-1)}});const retry=await json("/api/coaching/prompts",a,{body:{sessionId:w3.id,purpose:"dailyPlan"}});assert.equal(retry.prompt.id,failed.prompt.id);assert.equal(retry.prompt.attempts,2);assert.equal(retry.prompt.status,"simulated");const extra=await workout(a);await request("/api/coaching/prompts",a,{status:429,body:{sessionId:extra.id,purpose:"dailyPlan"}});});
 await scenario("Definite failure exhausts three recorded attempts and cannot trigger a fourth",async()=>{const a=await appCoach("retry-limit"),w=await workout(a),body={sessionId:w.id,purpose:"sessionFeedback",mockOutcome:"failed"};let p=await json("/api/coaching/prompts",a,{body});for(let attempt=2;attempt<=3;attempt++){await db.coachingPrompt.update({where:{id:p.prompt.id},data:{nextAttemptAt:new Date(Date.now()-1)}});p=await json("/api/coaching/prompts",a,{body});assert.equal(p.prompt.attempts,attempt);assert.equal(p.prompt.status,"failed");assert.equal(p.replyToken,null);}assert.equal(p.prompt.nextAttemptAt,null);await request("/api/coaching/prompts",a,{status:409,body});assert.equal(await db.coachingPrompt.count({where:{userId:a.id}}),1);assert.equal(await db.auditLog.count({where:{subjectId:a.id,action:"communication.mock-attempt"}}),3);});
 await scenario("Concurrent duplicate triggers create at most one prompt and one simulated attempt",async()=>{const a=await appCoach("concurrent-prompts"),w=await workout(a),body={sessionId:w.id,purpose:"sessionFeedback"};const res=await Promise.all([request("/api/coaching/prompts",a,{body}),request("/api/coaching/prompts",a,{body})]);assert.ok(res.some(r=>r.status===200));assert.ok(res.every(r=>[200,409].includes(r.status)));assert.equal(await db.coachingPrompt.count({where:{userId:a.id}}),1);assert.equal(await db.auditLog.count({where:{subjectId:a.id,action:"communication.mock-attempt"}}),1);});
 await scenario("Expired unconfirmed reply clears candidate and leaves no candidate values in audit copies",async()=>{const a=await appCoach("reply-retention"),w=await workout(a),p=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"sessionFeedback"}});await json("/api/coaching/replies",a,{body:reply(p,a.id,a.id,"status=partial; minutes=137; rpe=9; sport=run")});await db.coachingPrompt.update({where:{id:p.prompt.id},data:{repliedAt:new Date(Date.now()-8*86400000)}});const {runMockCoachingSchedule}=await import("../src/lib/coaching-service");await runMockCoachingSchedule();const saved=await db.coachingPrompt.findUniqueOrThrow({where:{id:p.prompt.id}});assert.equal(saved.replyStatus,"expired");assert.equal(saved.candidate,null);const logs=await db.auditLog.findMany({where:{subjectId:a.id}});assert.ok(!logs.some(log=>[log.before,log.after].some(value=>value?.includes('\"minutes\":137'))),"Expired unconfirmed actual values remain copied in an audit row");assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,null);});
 await scenario("Quiet hours and disabled individual purposes block prompts without saved attempts",async()=>{const a=await appCoach("quiet-purpose"),w=await workout(a);await json("/api/coaching/preferences",a,{method:"PUT",body:{...prefs(),sessionFeedback:false}});await request("/api/coaching/prompts",a,{status:409,body:{sessionId:w.id,purpose:"sessionFeedback"}});const min=new Date().getUTCHours()*60+new Date().getUTCMinutes();await json("/api/coaching/preferences",a,{method:"PUT",body:{...prefs(),quietStart:min,quietEnd:(min+3)%1440}});await request("/api/coaching/prompts",a,{status:409,body:{sessionId:w.id,purpose:"dailyPlan"}});assert.equal(await db.coachingPrompt.count({where:{userId:a.id}}),0);});
 await scenario("Current-day optional/safety-only prompts do not invent past completion questions or reply capability",async()=>{const a=await appCoach("optional-only"),w=await workout(a),p=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"missingData"}});assert.equal(p.replyToken,null);assert.ok(p.prompt.questions.every((q:any)=>q.appOnly));assert.ok(!p.prompt.questions.some((q:any)=>["status","minutes","rpe"].includes(q.key)));assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).feedbackStatus,null);});
 await scenario("Daily plan mock message stays source-revision bound and excludes sensitive free text",async()=>{const a=await appCoach("message-privacy"),w=await workout(a);const p=JSON.parse(w.prescription!);p.steps[0].note="SENSITIVE_MEDICAL_FIXTURE";await db.workout.update({where:{id:w.id},data:{prescription:JSON.stringify(p),notes:"SENSITIVE_MEDICAL_FIXTURE"}});const c=await current(a,w.id),prompt=await json("/api/coaching/prompts",a,{body:{sessionId:w.id,purpose:"dailyPlan"}});assert.equal(prompt.prompt.sourceRevision,c.revision);assert.match(prompt.prompt.message,/Before:/);assert.match(prompt.prompt.message,/During:/);assert.match(prompt.prompt.message,/After:/);assert.match(prompt.prompt.message,new RegExp(`/daily\\?sessionId=${w.id}`));assert.ok(!prompt.prompt.message.includes("SENSITIVE_MEDICAL_FIXTURE"));assert.equal(prompt.replyToken,null);assert.equal(prompt.prompt.externallySent,false);assert.equal(prompt.prompt.readAt,null);});
}
main().catch(e=>{results.push({name:"Runner setup",status:"FAIL",detail:String(e)});console.error(e);}).finally(async()=>{
 let cleanup=false;try{await db.usageCounter.deleteMany({where:{userId:{in:created}}});await db.appEvent.deleteMany({where:{userId:{in:created}}});await db.user.deleteMany({where:{id:{in:created}}});assert.equal(await db.user.count({where:{id:{in:created}}}),0);cleanup=true;}catch(e){results.push({name:"Fixture cleanup",status:"FAIL",detail:String(e)});}await db.$disconnect();
 let commit="unknown",sourceFingerprint:string|null=null;try{commit=execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();const files=execFileSync("git",["ls-files","--cached","--others","--exclude-standard"],{encoding:"utf8"}).split("\n").filter(p=>/^(src\/|scripts\/|prisma\/|package(?:-lock)?\.json$|next\.config\.mjs$)/.test(p)).sort();const hash=createHash("sha256");for(const p of files)hash.update(p).update("\0").update(readFileSync(p));sourceFingerprint=hash.digest("hex");}catch{}
 writeFileSync(`${dir}/report.json`,JSON.stringify({generatedAt:new Date().toISOString(),appMode:process.env.JMM_TEST_APP_MODE,buildId:process.env.JMM_TEST_BUILD_ID??null,commit,sourceFingerprint,mockedFonts:Boolean(process.env.NEXT_FONT_GOOGLE_MOCKED_RESPONSES),environment:"Private loopback PostgreSQL 17.6 and synthetic/mock-only app",results,artifacts,cleanup:{createdUsers:created.length,verified:cleanup},notRun:["Real provider delivery","Physical Garmin transfer","Live deployment","Browser interaction: prior ERR_BLOCKED_BY_CLIENT; no bypass"]},null,2));
 const failed=results.filter(x=>x.status==="FAIL");console.log(`${results.length-failed.length}/${results.length} followup acceptance scenarios passed.`);if(failed.length)process.exitCode=1;
});
