/** No socket/network calls: the adapter receives a test-only injected fetch. */
import test from "node:test";
import assert from "node:assert/strict";
import { sendTelegramCoaching, telegramCoachingConfigured, telegramCoachingEnabled, verifyTelegramWebhookSecret, parseTelegramUpdate } from "../src/lib/telegram-coaching-transport";
const env={ENABLE_TELEGRAM_COACHING:"true",ENABLE_AUTOMATED_DELIVERY:"true",COACHING_TRANSPORT:"telegram",TELEGRAM_BOT_TOKEN:"SYNTHETIC_NOT_A_VALID_BOT_TOKEN",TELEGRAM_COACHING_WEBHOOK_SECRET:"SYNTHETIC_LOCAL_WEBHOOK_SECRET"};
const response=(data:unknown,status=200)=>(async()=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json"}})) as typeof fetch;
test("All real-transport flags and credentials are required, default-off means zero requests",async()=>{
 assert.equal(telegramCoachingEnabled({}),false);assert.equal(telegramCoachingConfigured({}),false);
 for(const key of Object.keys(env)){let called=false;const result=await sendTelegramCoaching("123","Synthetic fixture",{env:{...env,[key]:undefined},fetcher:(async()=>{called=true;throw Error("Must not execute");}) as typeof fetch});assert.equal(called,false);assert.equal(result.status,"failed");}
});
test("Adapter uses fixed official endpoint, minimal body and verified accepted-recipient receipt",async()=>{
 let calls=0;const result=await sendTelegramCoaching("123","Synthetic fixture",{env,fetcher:(async(url,init)=>{calls++;const target=new URL(String(url));assert.equal(target.origin,"https://api.telegram.org");assert.equal(target.pathname,`/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`);assert.equal(init?.method,"POST");assert.equal(init?.redirect,"error");assert.ok(init?.signal);assert.deepEqual(JSON.parse(String(init?.body)),{chat_id:"123",text:"Synthetic fixture",link_preview_options:{is_disabled:true}});return new Response(JSON.stringify({ok:true,result:{message_id:42,chat:{id:123}}}));}) as typeof fetch});assert.equal(calls,1);assert.deepEqual(result,{status:"sent",receiptId:"telegram:42",error:null});
});
test("A Telegram sent receipt is not fabricated for wrong recipient, missing/invalid response or server ambiguity",async()=>{
 for(const data of [{ok:true,result:{message_id:42,chat:{id:999}}},{ok:true,result:{chat:{id:123}}},{ok:true},null,{}]){const r=await sendTelegramCoaching("123","Synthetic fixture",{env,fetcher:response(data)});assert.equal(r.status,"unknown");assert.equal(r.receiptId,null);}
 const invalid=await sendTelegramCoaching("123","Synthetic fixture",{env,fetcher:(async()=>new Response("not-json",{status:500})) as typeof fetch});assert.equal(invalid.status,"unknown");
});
test("Explicit API rejection is retryable failure and excludes private provider description",async()=>{const r=await sendTelegramCoaching("123","Synthetic fixture",{env,fetcher:response({ok:false,error_code:429,description:`PRIVATE ${env.TELEGRAM_BOT_TOKEN}`},429)});assert.equal(r.status,"failed");assert.equal(r.receiptId,null);assert.ok(!JSON.stringify(r).includes("PRIVATE"));assert.ok(!JSON.stringify(r).includes(env.TELEGRAM_BOT_TOKEN));});
test("Transport interruption is unknown, does not retry, and redacts request/provider secrets",async()=>{let calls=0;const r=await sendTelegramCoaching("123","PRIVATE_FIXTURE",{env,fetcher:(async()=>{calls++;throw Error(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage PRIVATE_FIXTURE`);}) as typeof fetch});assert.equal(r.status,"unknown");assert.equal(calls,1);assert.equal(r.receiptId,null);assert.ok(!JSON.stringify(r).includes(env.TELEGRAM_BOT_TOKEN));assert.ok(!JSON.stringify(r).includes("PRIVATE_FIXTURE"));});
test("Malformed recipient and oversize/blank messages never reach HTTP",async()=>{for(const[chat,text]of [["-123","text"],["https://other.invalid","text"],["123","x".repeat(4097)],["123"," "]]){let called=false;const r=await sendTelegramCoaching(chat,text,{env,fetcher:(async()=>{called=true;throw Error();})as typeof fetch});assert.equal(called,false);assert.equal(r.status,"failed");}});
test("Webhook secret requires exact equal byte content without throwing on malformed header",()=>{assert.equal(verifyTelegramWebhookSecret(env.TELEGRAM_COACHING_WEBHOOK_SECRET,env),true);for(const header of [null,"",env.TELEGRAM_COACHING_WEBHOOK_SECRET+"x","WRONG", "x".repeat(257)])assert.equal(verifyTelegramWebhookSecret(header,env),false);assert.equal(verifyTelegramWebhookSecret("known",{}),false);});
const now=new Date("2026-10-02T12:00:00Z"),token="a".repeat(43),revision="b".repeat(64);
const update=()=>({update_id:23,message:{text:`/reply ${token} session_1 2026-10-02 ${revision} status=unknown; minutes=unknown; rpe=unknown`,date:now.getTime()/1000,from:{id:123,is_bot:false},chat:{id:123,type:"private"}}});
test("Inbound grammar preserves session/date/revision and yields a candidate rather than interpreting narrative",()=>{const r=parseTelegramUpdate(update(),now);assert.equal(r.kind,"reply");if(r.kind!=="reply")return;assert.equal(r.sessionId,"session_1");assert.equal(r.sourceRevision,revision);assert.equal(r.observationDate,"2026-10-02");assert.equal(r.actorId,"123");assert.equal(r.chatId,"123");assert.match(r.text,/status=unknown/);const p=update();p.message.text=`/start ${token}`;assert.equal(parseTelegramUpdate(p,now).kind,"pair");});
test("Stale/future/group/bot/mismatched actor/edited-like and plain numeric updates reject",()=>{for(const change of [(u:ReturnType<typeof update>)=>u.message.date-=301,(u:ReturnType<typeof update>)=>u.message.date+=31,(u:ReturnType<typeof update>)=>u.message.chat.type="group",(u:ReturnType<typeof update>)=>u.message.from.is_bot=true,(u:ReturnType<typeof update>)=>u.message.from.id=456,(u:ReturnType<typeof update>)=>u.message.text="5"]){const u=update();change(u);assert.throws(()=>parseTelegramUpdate(u,now));}assert.throws(()=>parseTelegramUpdate({update_id:1,edited_message:update().message},now));});
test("Native Telegram reply UI sends force_reply without exposing session/token/revision",async()=>{let body:any;const r=await sendTelegramCoaching("123","Reply with status, minutes and RPE",{env,expectsReply:true,fetcher:(async(_url,init)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({ok:true,result:{message_id:51,chat:{id:123}}}));})as typeof fetch});assert.equal(r.status,"sent");assert.equal(body.reply_markup.force_reply,true);assert.equal(body.reply_markup.selective,true);assert.match(body.reply_markup.input_field_placeholder,/status=/);assert.ok(!/token|revision|sessionId/i.test(JSON.stringify(body)));});
test("Native reply parser binds original bot receipt and rejects forwarded or foreign original message",()=>{const source=()=>({...update(),message:{...update().message,text:"status=unknown; minutes=unknown; rpe=unknown",reply_to_message:{message_id:51,from:{is_bot:true},chat:{id:123}}}});const parsed=parseTelegramUpdate(source(),now);assert.equal(parsed.kind,"nativeReply");if(parsed.kind==="nativeReply")assert.equal(parsed.receiptId,"telegram:51");for(const mutate of [(u:any)=>u.message.reply_to_message.message_id=0,(u:any)=>u.message.reply_to_message.from.is_bot=false,(u:any)=>u.message.reply_to_message.chat.id=456,(u:any)=>u.message.forward_origin={type:"user"},(u:any)=>u.message.reply_to_message.forward_origin={type:"user"}]){const u=source();mutate(u);assert.throws(()=>parseTelegramUpdate(u,now));}});
test("Nonpositive or unsafe provider receipt IDs cannot be labeled sent",async()=>{for(const id of [0,-1,Number.MAX_SAFE_INTEGER+1]){const r=await sendTelegramCoaching("123","Synthetic fixture",{env,fetcher:response({ok:true,result:{message_id:id,chat:{id:123}}})});assert.equal(r.status,"unknown");assert.equal(r.receiptId,null);}});
