import { hashToken as hashSessionToken } from "../src/lib/auth";
import bcrypt from "bcryptjs";
/** Inbound-only Telegram HTTP acceptance, with synthetic DB rows and dummy config.
 * No Telegram request is permitted. A seeded sent prompt is a test fixture,
 * never evidence that any external provider accepted or delivered a message.
 */
import assert from "node:assert/strict";
import { randomBytes,randomUUID,createHash } from "node:crypto";
import { readFileSync,mkdirSync,writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { PrismaClient,type User } from "@prisma/client";
import { dayBounds } from "../src/lib/dates";
import { workoutRevision } from "../src/lib/workout-update";
import { newReplyToken } from "../src/lib/coaching-communication";
for(const key of ["DATABASE_URL","DIRECT_URL"]){const u=new URL(process.env[key]||"");assert.equal(u.protocol,"postgresql:");assert.equal(u.hostname,"127.0.0.1");assert.equal(u.port,"55432");assert.equal(u.pathname,"/jmm_launch_integration_test");assert.equal(u.search,"");}
assert.notEqual(process.env.VERCEL_ENV,"production");assert.equal(process.env.COACHING_TRANSPORT,"telegram");assert.equal(process.env.TELEGRAM_BOT_TOKEN,"SYNTHETIC_NOT_A_VALID_BOT_TOKEN");assert.equal(process.env.TELEGRAM_COACHING_WEBHOOK_SECRET,"SYNTHETIC_LOCAL_WEBHOOK_SECRET");
const db=new PrismaClient(),day=dayBounds("UTC").start,date=day.toISOString().slice(0,10),ids:string[]=[],updateIds:string[]=[],results:{name:string;status:"PASS"|"FAIL";detail?:string}[]=[];
const base="http://127.0.0.1:3220",path="/api/coaching/telegram/webhook",secret=process.env.TELEGRAM_COACHING_WEBHOOK_SECRET!;
type Actor=User&{cookie:string};
async function req(path:string,a?:Actor,body?:unknown,status=200,method=body===undefined?"GET":"POST",headers:Record<string,string>={}){const r=await fetch(base+path,{method,headers:{"content-type":"application/json",...(a?{cookie:a.cookie}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(120000)});if(r.status!==status)throw Error(`${method} ${path}: expected ${status}, got ${r.status}: ${(await r.text()).slice(0,600)}`);return r;}
async function json(path:string,a?:Actor,body?:unknown,status=200,method?:string){return(await req(path,a,body,status,method)).json();}
async function hook(body:unknown,status:number|"ignored"=200,header:string|null=secret){const result=await(await req(path,undefined,body,status==="ignored"?200:status,"POST",header===null?{}:{"x-telegram-bot-api-secret-token":header})).json();if(status==="ignored")assert.ok(result.ignored===true||result.duplicate===true,"Handled terminal updates must acknowledge without sensitive content");assert.equal(result.candidate,undefined);assert.equal(result.token,undefined);return result;}
async function scenario(name:string,run:()=>Promise<void>){try{await run();results.push({name,status:"PASS"});console.log(`PASS ${name}`);}catch(e){const detail=e instanceof Error?e.message:String(e);results.push({name,status:"FAIL",detail});console.error(`FAIL ${name}: ${detail}`);}}
async function actor(label:string):Promise<Actor>{const u=await db.user.create({data:{email:`webhook-${label}-${randomUUID()}@example.invalid`,name:`Synthetic webhook ${label}`,passwordHash:bcrypt.hashSync(randomBytes(32).toString("hex"),4),timezone:"UTC",language:"en",onboarded:true,profile:{create:{birthYear:1990,goal:"run-only",experience:"amateur",weeklyHours:3}},reminder:{create:{emailEnabled:false,telegramEnabled:false}}}});ids.push(u.id);const token=randomBytes(32).toString("hex");await db.authSession.create({data:{userId:u.id,tokenHash:hashSessionToken(token),expiresAt:new Date(Date.now()+7200000)}});const a={...u,cookie:`jmm_session=${token}`},p=await json("/api/profile",a);await json("/api/profile",a,{expectedRevision:p.revision,expectedSetupRevision:p.setupRevision??null,goal:"run-only",experience:"amateur",weeklyHours:3,birthYear:1990,setup:{adultConfirmed:true,profileConfirmed:true,goalDescription:"Synthetic safe general fitness",baselineWeeklyMinutes:120,baselineObservedAt:date,interruptions:"none",restrictions:"none",qualifiedReview:"none_needed",trainingDays:[1,3,5],maxSessionMinutes:60,equipmentAccess:"Running shoes",planWeeks:4}},200,"PUT");await db.dailyCheckin.create({data:{userId:a.id,date:day,answers:JSON.stringify({sleep:4,soreness:2,motivation:4,energy:4,stress:2,sick:false,newPain:false,urgentSymptoms:false,availableMin:120,inputMetadata:{version:"checkin-safety-v1",source:"athlete-reported",observedOn:date,recordedAt:new Date().toISOString()}}),adaptation:JSON.stringify({verdict:"full",durationFactor:1,intensityCap:"z7",safetyStatus:"clear",message:"Synthetic explicit safety answers"})}});return a;}
function settings(){const min=new Date().getUTCHours()*60+new Date().getUTCMinutes();return{primaryChannel:"telegram",paused:false,dailyPlan:true,sessionFeedback:true,missingData:true,timezone:"UTC",minuteOfDay:min,quietStart:(min+5)%1440,quietEnd:(min+6)%1440,declinedOptional:[],consentVersion:"telegram-coaching-v1"};}
function update(text:string,id=10020001){const updateId=Math.floor(Math.random()*100000000);updateIds.push(String(updateId));return{update_id:updateId,message:{date:Math.floor(Date.now()/1000),from:{id,is_bot:false},chat:{id,type:"private"},text}};}
async function pair(a:Actor,chat:number){const p=await json("/api/coaching/pairing",a,{});assert.equal(p.transport,"telegram");await hook(update(`/start ${p.token}`,chat));await json("/api/coaching/preferences",a,settings(),200,"PUT");}
async function seededPrompt(a:Actor){const p={title:"Synthetic inbound reply fixture",sport:"run",durationMin:20,intensity:"z2",type:"endurance",verdict:"full",steps:[{name:"Easy effort",phase:"active",zone:"z2",seconds:1200,target:{type:"open"}}]};const w=await db.workout.create({data:{userId:a.id,date:day,sport:"run",title:p.title,type:"endurance",durationMin:20,intensity:"z2",planned:true,source:"plan",prescription:JSON.stringify(p)}});const today=await json("/api/today",a),c=today.sessions.find((s:any)=>s.id===w.id);assert.ok(c?.revision);const token=newReplyToken();const prompt=await db.coachingPrompt.create({data:{userId:a.id,sessionId:w.id,purpose:"sessionFeedback",channel:"telegram",transport:"telegram",observationDate:date,timezone:"UTC",sourceRevision:c.revision,sourceWorkoutRevision:workoutRevision(w),idempotencyKey:randomUUID(),questions:"[]",message:"Synthetic seeded sent fixture, no external message",status:"sent",attempts:1,receiptId:`telegram:${Math.floor(Math.random()*100000000)+1}`,tokenHash:token.hash,tokenExpiresAt:token.expiresAt}});return{w,prompt,token:token.token,command:`/reply ${token.token} ${w.id} ${date} ${c.revision} status=partial; minutes=13; rpe=4; sport=run`};}

function nativeReply(receiptId:string,chat=10020001,text="status=partial; minutes=13; rpe=4; sport=run"){const u=update(text,chat);return{...u,message:{...u.message,reply_to_message:{message_id:Number(receiptId.split(":")[1]),from:{is_bot:true},chat:{id:chat}}}};}

async function main(){
 await scenario("Telegram webhook requires exact secret and bounded valid request body before processing",async()=>{await hook({},401,null);await hook({},401,"wrong");await hook({},"ignored");const malformed=await fetch(base+path,{method:"POST",headers:{"content-type":"application/json","x-telegram-bot-api-secret-token":secret},body:"{not-json"});assert.equal(malformed.status,400);await hook({data:"x".repeat(9000)},413);assert.equal(await db.coachingPrompt.count(),0);});
 const a=await actor("primary"),b=await actor("other");
 await scenario("Authenticated challenge pairs only a fresh private account and remains opted out until explicit consent",async()=>{await req("/api/coaching/pairing",undefined,{},401);const p=await json("/api/coaching/pairing",a,{});assert.equal(p.transport,"telegram");const wrong=update(`/start ${p.token}`);wrong.message.chat.type="group";await hook(wrong,"ignored");const paired=await hook(update(`/start ${p.token}`));assert.equal(paired.paired,true);assert.equal(paired.requiresConfirmation,false);const state=await json("/api/coaching/preferences",a);assert.equal(state.preferences.verificationTransport,"telegram");assert.equal(state.preferences.paused,true);assert.equal(state.preferences.dailyPlan,false);await hook(update(`/start ${p.token}`),"ignored");await req("/api/coaching/preferences",a,{...settings(),consentVersion:"mock-coaching-v1"},400,"PUT");await json("/api/coaching/preferences",a,settings(),200,"PUT");});
 await scenario("Webhook replies validate sender, freshness, bound session/date/revision and create only an app draft",async()=>{const f=await seededPrompt(a),before=await db.workout.findUnique({where:{id:f.w.id}});await hook(update(f.command,10020002),"ignored");const stale=update(f.command);stale.message.date-=301;await hook(stale,"ignored");const future=update(f.command);future.message.date+=60;await hook(future,"ignored");const bot=update(f.command);bot.message.from.is_bot=true;await hook(bot,"ignored");await hook(update(f.command.replace(f.w.id,"other-session")),"ignored");await hook(update(f.command.replace(date,"1999-01-01")),"ignored");await hook(update(f.command.replace(f.prompt.sourceRevision,"0".repeat(64))),"ignored");assert.deepEqual(await db.workout.findUnique({where:{id:f.w.id}}),before);const received=await hook(update(f.command));assert.equal(received.candidate,undefined);assert.equal(received.requiresConfirmation,true);const listed=await json("/api/coaching/prompts",a);const candidate=listed.prompts.find((p:any)=>p.id===f.prompt.id)?.candidate;assert.ok(candidate);assert.deepEqual(await db.workout.findUnique({where:{id:f.w.id}}),before);await hook(update(f.command),"ignored");await req("/api/coaching/replies",b,{promptId:f.prompt.id,action:"confirm",expectedRevision:f.prompt.sourceRevision,candidate},404,"PUT");const confirmed=await json("/api/coaching/replies",a,{promptId:f.prompt.id,action:"confirm",expectedRevision:f.prompt.sourceRevision,candidate:{...candidate,minutes:15}},200,"PUT");assert.equal(confirmed.applied,true);const saved=await db.workout.findUniqueOrThrow({where:{id:f.w.id}});assert.equal(saved.actualDurationMin,15);assert.equal(saved.rpe,4);assert.equal(saved.completed,false);await hook(update(f.command),"ignored");});
 await scenario("Native Telegram reply-to binds accepted receipt without technical tokens and rejects wrong/forwarded/chat receipts",async()=>{const f=await seededPrompt(a),receipt=f.prompt.receiptId!;const wrong=nativeReply(receipt);wrong.message.reply_to_message.message_id+=1;await hook(wrong,"ignored");await hook(nativeReply(receipt,10020002),"ignored");const forwarded:any=nativeReply(receipt);forwarded.message.forward_origin={type:"user"};await hook(forwarded,"ignored");const forwardedOriginal:any=nativeReply(receipt);forwardedOriginal.message.reply_to_message.forward_origin={type:"user"};await hook(forwardedOriginal,"ignored");const spoofed=nativeReply(receipt);spoofed.message.reply_to_message.from.is_bot=false;await hook(spoofed,"ignored");const old=nativeReply(receipt);old.message.date-=301;await hook(old,"ignored");const before=await db.workout.findUnique({where:{id:f.w.id}});const payload=nativeReply(receipt),draft=await hook(payload);assert.equal(draft.requiresConfirmation,true);assert.equal(draft.candidate,undefined);assert.deepEqual(await db.workout.findUnique({where:{id:f.w.id}}),before);await hook(payload,"ignored");await hook(nativeReply(receipt),"ignored");const listed=await json("/api/coaching/prompts",a),candidate=listed.prompts.find((p:any)=>p.id===f.prompt.id)?.candidate;assert.equal(candidate.minutes,13);await json("/api/coaching/replies",a,{promptId:f.prompt.id,action:"confirm",expectedRevision:f.prompt.sourceRevision,candidate},200,"PUT");assert.equal((await db.workout.findUniqueOrThrow({where:{id:f.w.id}})).actualDurationMin,13);});
 await scenario("Concurrent replay consumes exactly one reply token and writes one draft audit",async()=>{const f=await seededPrompt(a),payload=nativeReply(f.prompt.receiptId!);const responses=await Promise.all([fetch(base+path,{method:"POST",headers:{"content-type":"application/json","x-telegram-bot-api-secret-token":secret},body:JSON.stringify(payload)}),fetch(base+path,{method:"POST",headers:{"content-type":"application/json","x-telegram-bot-api-secret-token":secret},body:JSON.stringify(payload)})]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,200]);assert.equal(await db.auditLog.count({where:{subjectId:a.id,entityId:f.prompt.id,action:"coaching.reply.received"}}),1);assert.equal((await db.workout.findUniqueOrThrow({where:{id:f.w.id}})).actualDurationMin,null);});
 await scenario("Legacy incomplete processing marker resumes atomically and completed replay acknowledges without mutation",async()=>{const f=await seededPrompt(a),payload=nativeReply(f.prompt.receiptId!);await db.telegramCoachingUpdate.create({data:{id:String(payload.update_id),status:"processing",createdAt:new Date(Date.now()-60000)}});const resumed=await hook(payload);assert.equal(resumed.requiresConfirmation,true);assert.equal((await db.telegramCoachingUpdate.findUniqueOrThrow({where:{id:String(payload.update_id)}})).status,"drafted");const before=await db.coachingPrompt.findUnique({where:{id:f.prompt.id}});await hook(payload,"ignored");assert.deepEqual(await db.coachingPrompt.findUnique({where:{id:f.prompt.id}}),before);assert.equal(await db.auditLog.count({where:{entityId:f.prompt.id,action:"coaching.reply.received"}}),1);});
 await scenario("Transient failure after claim rolls back replay marker and draft, allowing the exact update to retry once",async()=>{const f=await seededPrompt(a),payload=nativeReply(f.prompt.receiptId!);await db.$executeRawUnsafe(`CREATE FUNCTION jmm_test_fail_reply_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action = 'coaching.reply.received' THEN RAISE EXCEPTION 'Synthetic transient reply audit failure'; END IF; RETURN NEW; END $$`);await db.$executeRawUnsafe(`CREATE TRIGGER jmm_test_fail_reply_audit BEFORE INSERT ON "AuditLog" FOR EACH ROW EXECUTE FUNCTION jmm_test_fail_reply_audit()`);try{await hook(payload,500);assert.equal(await db.telegramCoachingUpdate.findUnique({where:{id:String(payload.update_id)}}),null);const saved=await db.coachingPrompt.findUniqueOrThrow({where:{id:f.prompt.id}});assert.equal(saved.replyStatus,"none");assert.equal(saved.tokenUsedAt,null);assert.ok(saved.tokenHash);assert.equal(saved.candidate,null);assert.equal(await db.auditLog.count({where:{entityId:f.prompt.id,action:"coaching.reply.received"}}),0);}finally{await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS jmm_test_fail_reply_audit ON "AuditLog"`);await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS jmm_test_fail_reply_audit()`);}const retry=await hook(payload);assert.equal(retry.requiresConfirmation,true);await hook(payload,"ignored");assert.equal(await db.auditLog.count({where:{entityId:f.prompt.id,action:"coaching.reply.received"}}),1);assert.equal((await db.workout.findUniqueOrThrow({where:{id:f.w.id}})).actualDurationMin,null);});
 await scenario("Expired token and changed current session reject inbound mutation",async()=>{const f=await seededPrompt(a);await db.coachingPrompt.update({where:{id:f.prompt.id},data:{tokenExpiresAt:new Date(Date.now()-1000)}});await hook(nativeReply(f.prompt.receiptId!),"ignored");const changed=await seededPrompt(a);await db.workout.update({where:{id:changed.w.id},data:{notes:"Changed synthetic reviewed source"}});await hook(nativeReply(changed.prompt.receiptId!),"ignored");assert.equal((await db.workout.findUniqueOrThrow({where:{id:changed.w.id}})).actualDurationMin,null);});
 await scenario("Recipient cannot be rebound to another athlete; pause invalidates pending reply capabilities",async()=>{const p=await json("/api/coaching/pairing",b,{});await hook(update(`/start ${p.token}`),"ignored");assert.equal((await db.communicationPreference.findUniqueOrThrow({where:{userId:b.id}})).verifiedChatId,null);const f=await seededPrompt(a);await json("/api/coaching/preferences",a,{...settings(),paused:true},200,"PUT");await hook(nativeReply(f.prompt.receiptId!),"ignored");assert.equal((await db.workout.findUniqueOrThrow({where:{id:f.w.id}})).actualDurationMin,null);});
 await scenario("Disconnect removes verified recipient, consent, challenge and pending candidate capabilities",async()=>{const c=await actor("disconnect");await pair(c,10020003);const f=await seededPrompt(c);await hook(nativeReply(f.prompt.receiptId!,10020003));const result=await json("/api/coaching/pairing",c,undefined,200,"DELETE");assert.equal(result.disconnected,true);const pref=await db.communicationPreference.findUniqueOrThrow({where:{userId:c.id}});assert.equal(pref.verifiedChatId,null);assert.equal(pref.verifiedActorId,null);assert.equal(pref.challengeHash,null);assert.equal(pref.paused,true);assert.equal(pref.consentVersion,null);const prompt=await db.coachingPrompt.findUniqueOrThrow({where:{id:f.prompt.id}});assert.equal(prompt.candidate,null);assert.equal(prompt.tokenHash,null);assert.equal(prompt.replyStatus,"revoked");await hook(nativeReply(f.prompt.receiptId!,10020003),"ignored");});
 await outgoingServiceScenarios();
 await scenario("Webhook and pairing emit no provider request and expose no token/hash in list or audit",async()=>{const logs=await db.auditLog.findMany({where:{subjectId:{in:ids}}});assert.ok(!JSON.stringify(logs).includes(secret));assert.ok(!JSON.stringify(logs).includes(process.env.TELEGRAM_BOT_TOKEN!));const listed=await json("/api/coaching/prompts",a);assert.ok(listed.prompts.every((p:any)=>p.tokenHash===undefined));const attempts=readFileSync(process.env.JMM_EGRESS_LOG!,"utf8").trim().split("\n").filter(Boolean).map(x=>JSON.parse(x));assert.deepEqual(attempts.filter(x=>x.host!=="registry.npmjs.org"),[]);});
}
async function outgoingServiceScenarios(){
 const {createCoachingPrompt,disconnectCoaching,reconcileCoachingAttempts}=await import("../src/lib/coaching-service");
 async function prepared(label:string,chat:number){const a=await actor(label);await pair(a,chat);const f=await seededPrompt(a);await db.coachingPrompt.delete({where:{id:f.prompt.id}});return{a,w:f.w,chat};}
 await scenario("Real-mode service with injected adapter persists accepted receipt once and accepts native app-confirmed reply",async()=>{const{a,w,chat}=await prepared("dispatch-accepted",10020101);let calls=0;const dependencies={sendTelegram:async(recipient:string,text:string)=>{calls++;assert.equal(recipient,String(chat));assert.match(text,/reply/i);assert.ok(!text.includes("/reply "));assert.ok(!/[a-f0-9]{64}/.test(text));return{status:"sent"as const,receiptId:"telegram:501",error:null};}};const p=await createCoachingPrompt(a,{sessionId:w.id,purpose:"sessionFeedback"},new Date(),dependencies);assert.equal(p.prompt.status,"sent");assert.equal(p.prompt.receiptId,"telegram:501");assert.equal(p.replyToken,null);const duplicate=await createCoachingPrompt(a,{sessionId:w.id,purpose:"sessionFeedback"},new Date(),dependencies);assert.equal(duplicate.duplicate,true);assert.equal(calls,1);const before=await db.workout.findUnique({where:{id:w.id}});await hook(nativeReply("telegram:501",chat));assert.deepEqual(await db.workout.findUnique({where:{id:w.id}}),before);const listed=await json("/api/coaching/prompts",a),candidate=listed.prompts.find((x:any)=>x.id===p.prompt.id)?.candidate;await json("/api/coaching/replies",a,{promptId:p.prompt.id,action:"confirm",expectedRevision:p.prompt.sourceRevision,candidate},200,"PUT");assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,13);});
 await scenario("Real-mode definite failure retries only when due; unknown acceptance never resends",async()=>{const{a,w}=await prepared("dispatch-failed",10020102);let calls=0;const dependencies={sendTelegram:async()=>{calls++;return calls===1?{status:"failed"as const,receiptId:null,error:"Synthetic rejected before acceptance"}:{status:"sent"as const,receiptId:"telegram:502",error:null};}};const p=await createCoachingPrompt(a,{sessionId:w.id,purpose:"sessionFeedback"},new Date(),dependencies);assert.equal(p.prompt.status,"failed");assert.equal(p.replyToken,null);await assert.rejects(createCoachingPrompt(a,{sessionId:w.id,purpose:"sessionFeedback"},new Date(),dependencies));assert.equal(calls,1);await db.coachingPrompt.update({where:{id:p.prompt.id},data:{nextAttemptAt:new Date(Date.now()-1)}});const retry=await createCoachingPrompt(a,{sessionId:w.id,purpose:"sessionFeedback"},new Date(),dependencies);assert.equal(retry.prompt.status,"sent");assert.equal(retry.prompt.attempts,2);const u=await prepared("dispatch-unknown",10020103);let unknownCalls=0;const unknownDependencies={sendTelegram:async()=>{unknownCalls++;return{status:"unknown"as const,receiptId:null,error:"Synthetic timeout with unknown acceptance"};}};const unknown=await createCoachingPrompt(u.a,{sessionId:u.w.id,purpose:"sessionFeedback"},new Date(),unknownDependencies);assert.equal(unknown.prompt.status,"unknown");const repeated=await createCoachingPrompt(u.a,{sessionId:u.w.id,purpose:"sessionFeedback"},new Date(),unknownDependencies);assert.equal(repeated.duplicate,true);assert.equal(unknownCalls,1);assert.equal((await db.coachingPrompt.findUniqueOrThrow({where:{id:unknown.prompt.id}})).tokenHash,null);});
 await scenario("In-flight disconnect preserves revocation while recording late synthetic provider acceptance honestly",async()=>{const{a,w,chat}=await prepared("dispatch-disconnect",10020104);const p=await createCoachingPrompt(a,{sessionId:w.id,purpose:"sessionFeedback"},new Date(),{sendTelegram:async()=>{await disconnectCoaching(a);return{status:"sent",receiptId:"telegram:504",error:null};}});assert.equal(p.prompt.status,"cancelled");assert.equal(p.prompt.receiptId,"telegram:504");assert.match(p.prompt.error||"",/accepted.*cancellation|accepted.*reconciliation/i);assert.equal(p.prompt.externallySent,false);const saved=await db.coachingPrompt.findUniqueOrThrow({where:{id:p.prompt.id}});assert.equal(saved.tokenHash,null);assert.equal(saved.replyStatus,"revoked");await hook(nativeReply("telegram:504",chat),"ignored");assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,null);});
 await scenario("Interrupted pending dispatch becomes unknown with revoked nonce and no automatic resend",async()=>{const{a,w}=await prepared("dispatch-reconcile",10020105);const seed=await seededPrompt(a);await db.coachingPrompt.update({where:{id:seed.prompt.id},data:{status:"pending",lastAttemptAt:new Date(Date.now()-21*60000)}});await reconcileCoachingAttempts();const stored=await db.coachingPrompt.findUniqueOrThrow({where:{id:seed.prompt.id}});assert.equal(stored.status,"unknown");assert.equal(stored.tokenHash,null);assert.equal(stored.nextAttemptAt,null);assert.equal((await db.workout.findUniqueOrThrow({where:{id:w.id}})).actualDurationMin,null);});
}

main().catch(e=>{results.push({name:"Runner setup",status:"FAIL",detail:String(e)});console.error(e);}).finally(async()=>{let cleaned=false;try{await db.telegramCoachingUpdate.deleteMany({where:{id:{in:updateIds}}});await db.usageCounter.deleteMany({where:{userId:{in:ids}}});await db.appEvent.deleteMany({where:{userId:{in:ids}}});await db.user.deleteMany({where:{id:{in:ids}}});assert.equal(await db.user.count({where:{id:{in:ids}}}),0);cleaned=true;}catch(e){results.push({name:"Synthetic cleanup",status:"FAIL",detail:String(e)});}await db.$disconnect();let commit="unknown",sourceFingerprint:string|null=null;try{commit=execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();const files=execFileSync("git",["ls-files","--cached","--others","--exclude-standard"],{encoding:"utf8"}).split("\n").filter(p=>/^(src\/|scripts\/|prisma\/|package(?:-lock)?\.json$|next\.config\.mjs$)/.test(p)).sort();const hash=createHash("sha256");for(const p of files)hash.update(p).update("\0").update(readFileSync(p));sourceFingerprint=hash.digest("hex");}catch{}mkdirSync(".local/jmm-telegram-webhook-integration",{recursive:true});writeFileSync(".local/jmm-telegram-webhook-integration/report.json",JSON.stringify({generatedAt:new Date().toISOString(),appMode:process.env.JMM_TEST_APP_MODE,buildId:process.env.JMM_TEST_BUILD_ID??null,commit,sourceFingerprint,scope:"Loopback inbound HTTP and server-only injected outbound adapter. Synthetic receipts are test fixtures, never real provider acceptance. Dummy configuration, egress guarded.",results,cleanup:{created:ids.length,verified:cleaned},liveTelegram:"NOT RUN"},null,2));const fail=results.filter(x=>x.status==="FAIL").length;console.log(`${results.length-fail}/${results.length} inbound webhook scenarios passed`);if(fail)process.exitCode=1;});
